package com.huanshankeji.compose.material3

import androidx.compose.runtime.Composable
import com.huanshankeji.compose.foundation.ext.matchPositionRelativeParent
import com.huanshankeji.compose.foundation.layout.PaddingValues
import com.huanshankeji.compose.foundation.layout.ext.fillMaxSizeStretch
import com.huanshankeji.compose.ui.Modifier
import com.huanshankeji.compose.ui.toAttrs
import com.varabyte.kobweb.compose.css.TextAlign
import com.varabyte.kobweb.compose.css.textAlign
import org.jetbrains.compose.web.css.*
import org.jetbrains.compose.web.dom.Div

// adapted from `TopAppBarScaffold.js.kt` in `com.huanshankeji.compose.material2.ext`

// TODO Can this be implemented using the `Box`, Column` wrappers instead of HTML and CSS primitives?
@Composable
actual fun Scaffold(
    modifier: Modifier,
    topBar: @Composable () -> Unit,
    bottomBar: @Composable () -> Unit,
    snackbarHost: @Composable () -> Unit,
    floatingActionButton: @Composable () -> Unit,
    floatingActionButtonPosition: FabPosition,
    content: @Composable (PaddingValues) -> Unit,
) {
    @Composable
    fun FabWithPosition() =
        Div({
            style {
                position(Position.Absolute)
                bottom(16.px)
                when (floatingActionButtonPosition) {
                    FabPosition.Start -> left(16.px)
                    FabPosition.Center -> {
                        width(100.percent)
                        textAlign(TextAlign.Center)
                    }

                    FabPosition.End, FabPosition.EndOverlay -> right(16.px)
                }
            }
        }) {
            floatingActionButton()
        }

    Div(Modifier.fillMaxSizeStretch().then(modifier).toAttrs {
        style {
            display(DisplayStyle.Flex)
            flexDirection(FlexDirection.Column)
            position(Position.Relative)
        }
    }) {
        topBar()

        // Main content area: fills remaining vertical space between top bar and bottom bar
        // This part has nested `Div`s but works. Adapted from the Material 2 TopAppBarScaffold JS implementation.
        Div({
            style {
                // Generated by Copilot. These 3 lines implement the "flex item fills remaining space" pattern.
                flexGrow(1)
                //flexShrink(1) // This can be removed. Confirmed by Copilot.
                flexBasis(0.px)
                position(Position.Relative)
            }
        }) {
            Div({
                style {
                    matchPositionRelativeParent()
                }
            }) {
                // TODO See https://issues.chromium.org/issues/386052671. This can be removed when the issue is fixed, possibly by partially reverting commit fb269bdfa876bc63402c68a025325f42b8a8abec.
                // This nested `Div` is here so that a child using `fillMaxSizeStretch` works properly. `fillMaxSizeStretch` seems buggy when used directly in the `position: absolute` parent.
                Div({
                    style {
                        height(100.percent)
                    }
                }) {
                    content(PaddingValues())
                }
            }

            // FAB for Start/Center/End positions: inside content area, above bottom bar
            if (floatingActionButtonPosition != FabPosition.EndOverlay) {
                FabWithPosition()
            }

            // Snackbar host: absolutely positioned at bottom center, above FAB, matching Compose UI Scaffold behavior.
            // The bottom offset (88px) accounts for the FAB area: 16px (FAB bottom) + 56px (standard FAB height) + 16px (gap).
            // TODO these values should be computed dynamically if the FAB size changes.
            Div({
                style {
                    position(Position.Absolute)
                    // TODO not working properly with `FabPosition.EndOverlay`
                    bottom(88.px)
                    left(0.px)
                    right(0.px)
                    display(DisplayStyle.Flex)
                    justifyContent(JustifyContent.Center)
                    // TODO remove these if they are not needed
                    property("pointer-events", "none")
                    property("z-index", "10")
                }
            }) {
                Div({
                    style {
                        property("pointer-events", "auto")
                    }
                }) {
                    snackbarHost()
                }
            }
        }

        bottomBar()

        // FAB for EndOverlay position: overlays bottom bar
        if (floatingActionButtonPosition == FabPosition.EndOverlay) {
            FabWithPosition()
        }
    }
}
