// generated by Copilot and not reviewed line by line

package com.huanshankeji.compose.material.icons.filled

import androidx.compose.material.icons.filled.*
import com.huanshankeji.compose.material.icons.Icon
import com.huanshankeji.compose.material.icons.Icons
import androidx.compose.material.icons.Icons as PlatformIcons

actual val Icons.Filled.AccountBox: Icon get() = PlatformIcons.Filled.AccountBox
actual val Icons.Filled.AccountCircle: Icon get() = PlatformIcons.Filled.AccountCircle
actual val Icons.Filled.Add: Icon get() = PlatformIcons.Filled.Add
actual val Icons.Filled.AddCircle: Icon get() = PlatformIcons.Filled.AddCircle
actual val Icons.Filled.ArrowBack: Icon get() = PlatformIcons.Filled.ArrowBack
actual val Icons.Filled.ArrowDropDown: Icon get() = PlatformIcons.Filled.ArrowDropDown
actual val Icons.Filled.ArrowForward: Icon get() = PlatformIcons.Filled.ArrowForward
actual val Icons.Filled.Build: Icon get() = PlatformIcons.Filled.Build
actual val Icons.Filled.Call: Icon get() = PlatformIcons.Filled.Call
actual val Icons.Filled.Check: Icon get() = PlatformIcons.Filled.Check
actual val Icons.Filled.CheckCircle: Icon get() = PlatformIcons.Filled.CheckCircle
actual val Icons.Filled.Close: Icon get() = PlatformIcons.Filled.Close
actual val Icons.Filled.DateRange: Icon get() = PlatformIcons.Filled.DateRange
actual val Icons.Filled.Delete: Icon get() = PlatformIcons.Filled.Delete
actual val Icons.Filled.Done: Icon get() = PlatformIcons.Filled.Done
actual val Icons.Filled.Edit: Icon get() = PlatformIcons.Filled.Edit
actual val Icons.Filled.ExitToApp: Icon get() = PlatformIcons.Filled.ExitToApp
actual val Icons.Filled.Face: Icon get() = PlatformIcons.Filled.Face
actual val Icons.Filled.Favorite: Icon get() = PlatformIcons.Filled.Favorite
actual val Icons.Filled.Home: Icon get() = PlatformIcons.Filled.Home
actual val Icons.Filled.Info: Icon get() = PlatformIcons.Filled.Info
actual val Icons.Filled.KeyboardArrowDown: Icon get() = PlatformIcons.Filled.KeyboardArrowDown
actual val Icons.Filled.KeyboardArrowLeft: Icon get() = PlatformIcons.Filled.KeyboardArrowLeft
actual val Icons.Filled.KeyboardArrowRight: Icon get() = PlatformIcons.Filled.KeyboardArrowRight
actual val Icons.Filled.KeyboardArrowUp: Icon get() = PlatformIcons.Filled.KeyboardArrowUp
actual val Icons.Filled.List: Icon get() = PlatformIcons.Filled.List
actual val Icons.Filled.Lock: Icon get() = PlatformIcons.Filled.Lock
actual val Icons.Filled.Menu: Icon get() = PlatformIcons.Filled.Menu
actual val Icons.Filled.MoreVert: Icon get() = PlatformIcons.Filled.MoreVert
actual val Icons.Filled.Notifications: Icon get() = PlatformIcons.Filled.Notifications
actual val Icons.Filled.Person: Icon get() = PlatformIcons.Filled.Person
actual val Icons.Filled.Place: Icon get() = PlatformIcons.Filled.Place
actual val Icons.Filled.PlayArrow: Icon get() = PlatformIcons.Filled.PlayArrow
actual val Icons.Filled.Refresh: Icon get() = PlatformIcons.Filled.Refresh
actual val Icons.Filled.Search: Icon get() = PlatformIcons.Filled.Search
actual val Icons.Filled.Send: Icon get() = PlatformIcons.Filled.Send
actual val Icons.Filled.Settings: Icon get() = PlatformIcons.Filled.Settings
actual val Icons.Filled.Share: Icon get() = PlatformIcons.Filled.Share
actual val Icons.Filled.ShoppingCart: Icon get() = PlatformIcons.Filled.ShoppingCart
actual val Icons.Filled.Star: Icon get() = PlatformIcons.Filled.Star
actual val Icons.Filled.ThumbUp: Icon get() = PlatformIcons.Filled.ThumbUp
actual val Icons.Filled.Warning: Icon get() = PlatformIcons.Filled.Warning
