package com.huanshankeji.compose.material.demo

import com.huanshankeji.compose.material.icons.Icon
import com.huanshankeji.compose.material.icons.Icons
import com.huanshankeji.compose.material.icons.automirrored.filled.*
import com.huanshankeji.compose.material.icons.filled.*

val coreFilledIconNamePairs: List<Pair<String, Icon>> = listOf(
    "Account Box" to Icons.Filled.AccountBox,
    "Account Circle" to Icons.Filled.AccountCircle,
    "Add" to Icons.Filled.Add,
    "Add Circle" to Icons.Filled.AddCircle,
    "Arrow Back" to Icons.Filled.ArrowBack,
    "Arrow Drop Down" to Icons.Filled.ArrowDropDown,
    "Arrow Forward" to Icons.Filled.ArrowForward,
    "Build" to Icons.Filled.Build,
    "Call" to Icons.Filled.Call,
    "Check" to Icons.Filled.Check,
    "Check Circle" to Icons.Filled.CheckCircle,
    "Close" to Icons.Filled.Close,
    "Date Range" to Icons.Filled.DateRange,
    "Delete" to Icons.Filled.Delete,
    "Done" to Icons.Filled.Done,
    "Edit" to Icons.Filled.Edit,
    "Exit To App" to Icons.Filled.ExitToApp,
    "Face" to Icons.Filled.Face,
    "Favorite" to Icons.Filled.Favorite,
    "Home" to Icons.Filled.Home,
    "Info" to Icons.Filled.Info,
    "Keyboard Arrow Down" to Icons.Filled.KeyboardArrowDown,
    "Keyboard Arrow Left" to Icons.Filled.KeyboardArrowLeft,
    "Keyboard Arrow Right" to Icons.Filled.KeyboardArrowRight,
    "Keyboard Arrow Up" to Icons.Filled.KeyboardArrowUp,
    "List" to Icons.Filled.List,
    "Lock" to Icons.Filled.Lock,
    "Menu" to Icons.Filled.Menu,
    "More Vert" to Icons.Filled.MoreVert,
    "Notifications" to Icons.Filled.Notifications,
    "Person" to Icons.Filled.Person,
    "Place" to Icons.Filled.Place,
    "Play Arrow" to Icons.Filled.PlayArrow,
    "Refresh" to Icons.Filled.Refresh,
    "Search" to Icons.Filled.Search,
    "Send" to Icons.Filled.Send,
    "Settings" to Icons.Filled.Settings,
    "Share" to Icons.Filled.Share,
    "Shopping Cart" to Icons.Filled.ShoppingCart,
    "Star" to Icons.Filled.Star,
    "Thumb Up" to Icons.Filled.ThumbUp,
    "Warning" to Icons.Filled.Warning,
)

val coreAutoMirroredFilledIconNamePairs: List<Pair<String, Icon>> = listOf(
    "Arrow Back" to Icons.AutoMirrored.Filled.ArrowBack,
    "Arrow Forward" to Icons.AutoMirrored.Filled.ArrowForward,
    "Exit To App" to Icons.AutoMirrored.Filled.ExitToApp,
    "Keyboard Arrow Left" to Icons.AutoMirrored.Filled.KeyboardArrowLeft,
    "Keyboard Arrow Right" to Icons.AutoMirrored.Filled.KeyboardArrowRight,
    "List" to Icons.AutoMirrored.Filled.List,
    "Send" to Icons.AutoMirrored.Filled.Send,
)

val extendedOnlyFilledIconNamePairs: List<Pair<String, Icon>> = listOf(
    "Abc" to Icons.Filled.Abc,
    "Ac Unit" to Icons.Filled.AcUnit,
    "Accessibility" to Icons.Filled.Accessibility,
    "Accessibility New" to Icons.Filled.AccessibilityNew,
    "Accessible" to Icons.Filled.Accessible,
    "Accessible Forward" to Icons.Filled.AccessibleForward,
    "Account Balance" to Icons.Filled.AccountBalance,
    "Account Balance Wallet" to Icons.Filled.AccountBalanceWallet,
    "Account Tree" to Icons.Filled.AccountTree,
    "Adb" to Icons.Filled.Adb,
    "Add A Photo" to Icons.Filled.AddAPhoto,
    "Add Alert" to Icons.Filled.AddAlert,
    "Add Box" to Icons.Filled.AddBox,
    "Add Business" to Icons.Filled.AddBusiness,
    "Add Card" to Icons.Filled.AddCard,
    "Add Chart" to Icons.Filled.AddChart,
    "Add Comment" to Icons.Filled.AddComment,
    "Add Home" to Icons.Filled.AddHome,
    "Add Home Work" to Icons.Filled.AddHomeWork,
    "Add Link" to Icons.Filled.AddLink,
    "Add Location" to Icons.Filled.AddLocation,
    "Add Location Alt" to Icons.Filled.AddLocationAlt,
    "Add Moderator" to Icons.Filled.AddModerator,
    "Add Photo Alternate" to Icons.Filled.AddPhotoAlternate,
    "Add Reaction" to Icons.Filled.AddReaction,
    "Add Road" to Icons.Filled.AddRoad,
    "Add Shopping Cart" to Icons.Filled.AddShoppingCart,
    "Add Task" to Icons.Filled.AddTask,
    "Add To Drive" to Icons.Filled.AddToDrive,
    "Add To Photos" to Icons.Filled.AddToPhotos,
    "Add To Queue" to Icons.Filled.AddToQueue,
    "Adf Scanner" to Icons.Filled.AdfScanner,
    "Adjust" to Icons.Filled.Adjust,
    "Admin Panel Settings" to Icons.Filled.AdminPanelSettings,
    "Ads Click" to Icons.Filled.AdsClick,
    "Agriculture" to Icons.Filled.Agriculture,
    "Air" to Icons.Filled.Air,
    "Airline Seat Flat" to Icons.Filled.AirlineSeatFlat,
    "Airline Seat Flat Angled" to Icons.Filled.AirlineSeatFlatAngled,
    "Airline Seat Individual Suite" to Icons.Filled.AirlineSeatIndividualSuite,
    "Airline Seat Legroom Extra" to Icons.Filled.AirlineSeatLegroomExtra,
    "Airline Seat Legroom Normal" to Icons.Filled.AirlineSeatLegroomNormal,
    "Airline Seat Legroom Reduced" to Icons.Filled.AirlineSeatLegroomReduced,
    "Airline Seat Recline Extra" to Icons.Filled.AirlineSeatReclineExtra,
    "Airline Seat Recline Normal" to Icons.Filled.AirlineSeatReclineNormal,
    "Airline Stops" to Icons.Filled.AirlineStops,
    "Airlines" to Icons.Filled.Airlines,
    "Airplane Ticket" to Icons.Filled.AirplaneTicket,
    "Airplanemode Active" to Icons.Filled.AirplanemodeActive,
    "Airplanemode Inactive" to Icons.Filled.AirplanemodeInactive,
    "Airplay" to Icons.Filled.Airplay,
    "Airport Shuttle" to Icons.Filled.AirportShuttle,
    "Alarm" to Icons.Filled.Alarm,
    "Alarm Add" to Icons.Filled.AlarmAdd,
    "Alarm Off" to Icons.Filled.AlarmOff,
    "Alarm On" to Icons.Filled.AlarmOn,
    "Album" to Icons.Filled.Album,
    "Align Horizontal Center" to Icons.Filled.AlignHorizontalCenter,
    "Align Horizontal Left" to Icons.Filled.AlignHorizontalLeft,
    "Align Horizontal Right" to Icons.Filled.AlignHorizontalRight,
    "Align Vertical Bottom" to Icons.Filled.AlignVerticalBottom,
    "Align Vertical Center" to Icons.Filled.AlignVerticalCenter,
    "Align Vertical Top" to Icons.Filled.AlignVerticalTop,
    "All Inbox" to Icons.Filled.AllInbox,
    "All Inclusive" to Icons.Filled.AllInclusive,
    "All Out" to Icons.Filled.AllOut,
    "Alt Route" to Icons.Filled.AltRoute,
    "Alternate Email" to Icons.Filled.AlternateEmail,
    "Amp Stories" to Icons.Filled.AmpStories,
    "Analytics" to Icons.Filled.Analytics,
    "Anchor" to Icons.Filled.Anchor,
    "Android" to Icons.Filled.Android,
    "Animation" to Icons.Filled.Animation,
    "Apartment" to Icons.Filled.Apartment,
    "Api" to Icons.Filled.Api,
    "App Registration" to Icons.Filled.AppRegistration,
    "Approval" to Icons.Filled.Approval,
    "Apps" to Icons.Filled.Apps,
    "Apps Outage" to Icons.Filled.AppsOutage,
    "Architecture" to Icons.Filled.Architecture,
    "Archive" to Icons.Filled.Archive,
    "Area Chart" to Icons.Filled.AreaChart,
    "Arrow Back Ios" to Icons.Filled.ArrowBackIos,
    "Arrow Back Ios New" to Icons.Filled.ArrowBackIosNew,
    "Arrow Circle Down" to Icons.Filled.ArrowCircleDown,
    "Arrow Circle Left" to Icons.Filled.ArrowCircleLeft,
    "Arrow Circle Right" to Icons.Filled.ArrowCircleRight,
    "Arrow Circle Up" to Icons.Filled.ArrowCircleUp,
    "Arrow Downward" to Icons.Filled.ArrowDownward,
    "Arrow Drop Down Circle" to Icons.Filled.ArrowDropDownCircle,
    "Arrow Drop Up" to Icons.Filled.ArrowDropUp,
    "Arrow Forward Ios" to Icons.Filled.ArrowForwardIos,
    "Arrow Left" to Icons.Filled.ArrowLeft,
    "Arrow Outward" to Icons.Filled.ArrowOutward,
    "Arrow Right" to Icons.Filled.ArrowRight,
    "Arrow Right Alt" to Icons.Filled.ArrowRightAlt,
    "Arrow Upward" to Icons.Filled.ArrowUpward,
    "Art Track" to Icons.Filled.ArtTrack,
    "Article" to Icons.Filled.Article,
    "Aspect Ratio" to Icons.Filled.AspectRatio,
    "Assignment" to Icons.Filled.Assignment,
    "Assignment Ind" to Icons.Filled.AssignmentInd,
    "Assignment Late" to Icons.Filled.AssignmentLate,
    "Assignment Return" to Icons.Filled.AssignmentReturn,
    "Assignment Returned" to Icons.Filled.AssignmentReturned,
    "Assignment Turned In" to Icons.Filled.AssignmentTurnedIn,
    "Assist Walker" to Icons.Filled.AssistWalker,
    "Assistant" to Icons.Filled.Assistant,
    "Assistant Direction" to Icons.Filled.AssistantDirection,
    "Assured Workload" to Icons.Filled.AssuredWorkload,
    "Atm" to Icons.Filled.Atm,
    "Attach Email" to Icons.Filled.AttachEmail,
    "Attach File" to Icons.Filled.AttachFile,
    "Attach Money" to Icons.Filled.AttachMoney,
    "Attachment" to Icons.Filled.Attachment,
    "Attractions" to Icons.Filled.Attractions,
    "Attribution" to Icons.Filled.Attribution,
    "Audio File" to Icons.Filled.AudioFile,
    "Auto Awesome" to Icons.Filled.AutoAwesome,
    "Auto Awesome Mosaic" to Icons.Filled.AutoAwesomeMosaic,
    "Auto Awesome Motion" to Icons.Filled.AutoAwesomeMotion,
    "Auto Delete" to Icons.Filled.AutoDelete,
    "Auto Fix Normal" to Icons.Filled.AutoFixNormal,
    "Auto Fix Off" to Icons.Filled.AutoFixOff,
    "Auto Graph" to Icons.Filled.AutoGraph,
    "Auto Mode" to Icons.Filled.AutoMode,
    "Auto Stories" to Icons.Filled.AutoStories,
    "Autofps Select" to Icons.Filled.AutofpsSelect,
    "Autorenew" to Icons.Filled.Autorenew,
    "Av Timer" to Icons.Filled.AvTimer,
    "Baby Changing Station" to Icons.Filled.BabyChangingStation,
    "Back Hand" to Icons.Filled.BackHand,
    "Backpack" to Icons.Filled.Backpack,
    "Backspace" to Icons.Filled.Backspace,
    "Backup" to Icons.Filled.Backup,
    "Backup Table" to Icons.Filled.BackupTable,
    "Badge" to Icons.Filled.Badge,
    "Bakery Dining" to Icons.Filled.BakeryDining,
    "Balance" to Icons.Filled.Balance,
    "Balcony" to Icons.Filled.Balcony,
    "Ballot" to Icons.Filled.Ballot,
    "Bar Chart" to Icons.Filled.BarChart,
    "Batch Prediction" to Icons.Filled.BatchPrediction,
    "Bathroom" to Icons.Filled.Bathroom,
    "Bathtub" to Icons.Filled.Bathtub,
    "Battery0 Bar" to Icons.Filled.Battery0Bar,
    "Battery1 Bar" to Icons.Filled.Battery1Bar,
    "Battery2 Bar" to Icons.Filled.Battery2Bar,
    "Battery3 Bar" to Icons.Filled.Battery3Bar,
    "Battery4 Bar" to Icons.Filled.Battery4Bar,
    "Battery5 Bar" to Icons.Filled.Battery5Bar,
    "Battery6 Bar" to Icons.Filled.Battery6Bar,
    "Battery Alert" to Icons.Filled.BatteryAlert,
    "Battery Charging Full" to Icons.Filled.BatteryChargingFull,
    "Battery Full" to Icons.Filled.BatteryFull,
    "Battery Saver" to Icons.Filled.BatterySaver,
    "Battery Unknown" to Icons.Filled.BatteryUnknown,
    "Beach Access" to Icons.Filled.BeachAccess,
    "Bed" to Icons.Filled.Bed,
    "Bedroom Baby" to Icons.Filled.BedroomBaby,
    "Bedroom Child" to Icons.Filled.BedroomChild,
    "Bedroom Parent" to Icons.Filled.BedroomParent,
    "Bedtime" to Icons.Filled.Bedtime,
    "Bedtime Off" to Icons.Filled.BedtimeOff,
    "Beenhere" to Icons.Filled.Beenhere,
    "Bento" to Icons.Filled.Bento,
    "Bike Scooter" to Icons.Filled.BikeScooter,
    "Biotech" to Icons.Filled.Biotech,
    "Blender" to Icons.Filled.Blender,
    "Blind" to Icons.Filled.Blind,
    "Blinds" to Icons.Filled.Blinds,
    "Blinds Closed" to Icons.Filled.BlindsClosed,
    "Block" to Icons.Filled.Block,
    "Bloodtype" to Icons.Filled.Bloodtype,
    "Bluetooth" to Icons.Filled.Bluetooth,
    "Bluetooth Connected" to Icons.Filled.BluetoothConnected,
    "Bluetooth Disabled" to Icons.Filled.BluetoothDisabled,
    "Bluetooth Drive" to Icons.Filled.BluetoothDrive,
    "Bluetooth Searching" to Icons.Filled.BluetoothSearching,
    "Blur Circular" to Icons.Filled.BlurCircular,
    "Blur Linear" to Icons.Filled.BlurLinear,
    "Blur Off" to Icons.Filled.BlurOff,
    "Blur On" to Icons.Filled.BlurOn,
    "Bolt" to Icons.Filled.Bolt,
    "Book" to Icons.Filled.Book,
    "Bookmark" to Icons.Filled.Bookmark,
    "Bookmark Add" to Icons.Filled.BookmarkAdd,
    "Bookmark Added" to Icons.Filled.BookmarkAdded,
    "Bookmark Remove" to Icons.Filled.BookmarkRemove,
    "Bookmarks" to Icons.Filled.Bookmarks,
    "Border All" to Icons.Filled.BorderAll,
    "Border Bottom" to Icons.Filled.BorderBottom,
    "Border Clear" to Icons.Filled.BorderClear,
    "Border Color" to Icons.Filled.BorderColor,
    "Border Horizontal" to Icons.Filled.BorderHorizontal,
    "Border Inner" to Icons.Filled.BorderInner,
    "Border Left" to Icons.Filled.BorderLeft,
    "Border Outer" to Icons.Filled.BorderOuter,
    "Border Right" to Icons.Filled.BorderRight,
    "Border Style" to Icons.Filled.BorderStyle,
    "Border Top" to Icons.Filled.BorderTop,
    "Border Vertical" to Icons.Filled.BorderVertical,
    "Boy" to Icons.Filled.Boy,
    "Branding Watermark" to Icons.Filled.BrandingWatermark,
    "Breakfast Dining" to Icons.Filled.BreakfastDining,
    "Brightness1" to Icons.Filled.Brightness1,
    "Brightness2" to Icons.Filled.Brightness2,
    "Brightness3" to Icons.Filled.Brightness3,
    "Brightness4" to Icons.Filled.Brightness4,
    "Brightness5" to Icons.Filled.Brightness5,
    "Brightness6" to Icons.Filled.Brightness6,
    "Brightness7" to Icons.Filled.Brightness7,
    "Brightness Auto" to Icons.Filled.BrightnessAuto,
    "Brightness High" to Icons.Filled.BrightnessHigh,
    "Brightness Low" to Icons.Filled.BrightnessLow,
    "Brightness Medium" to Icons.Filled.BrightnessMedium,
    "Broadcast On Home" to Icons.Filled.BroadcastOnHome,
    "Broadcast On Personal" to Icons.Filled.BroadcastOnPersonal,
    "Broken Image" to Icons.Filled.BrokenImage,
    "Browse Gallery" to Icons.Filled.BrowseGallery,
    "Browser Updated" to Icons.Filled.BrowserUpdated,
    "Brunch Dining" to Icons.Filled.BrunchDining,
    "Brush" to Icons.Filled.Brush,
    "Bubble Chart" to Icons.Filled.BubbleChart,
    "Bug Report" to Icons.Filled.BugReport,
    "Build Circle" to Icons.Filled.BuildCircle,
    "Bungalow" to Icons.Filled.Bungalow,
    "Burst Mode" to Icons.Filled.BurstMode,
    "Bus Alert" to Icons.Filled.BusAlert,
    "Business Center" to Icons.Filled.BusinessCenter,
    "Cabin" to Icons.Filled.Cabin,
    "Cable" to Icons.Filled.Cable,
    "Cached" to Icons.Filled.Cached,
    "Cake" to Icons.Filled.Cake,
    "Calculate" to Icons.Filled.Calculate,
    "Calendar Month" to Icons.Filled.CalendarMonth,
    "Calendar Today" to Icons.Filled.CalendarToday,
    "Calendar View Day" to Icons.Filled.CalendarViewDay,
    "Calendar View Month" to Icons.Filled.CalendarViewMonth,
    "Calendar View Week" to Icons.Filled.CalendarViewWeek,
    "Call End" to Icons.Filled.CallEnd,
    "Call Made" to Icons.Filled.CallMade,
    "Call Merge" to Icons.Filled.CallMerge,
    "Call Missed" to Icons.Filled.CallMissed,
    "Call Missed Outgoing" to Icons.Filled.CallMissedOutgoing,
    "Call Received" to Icons.Filled.CallReceived,
    "Call Split" to Icons.Filled.CallSplit,
    "Call To Action" to Icons.Filled.CallToAction,
    "Camera" to Icons.Filled.Camera,
    "Camera Enhance" to Icons.Filled.CameraEnhance,
    "Camera Indoor" to Icons.Filled.CameraIndoor,
    "Camera Outdoor" to Icons.Filled.CameraOutdoor,
    "Camera Roll" to Icons.Filled.CameraRoll,
    "Cameraswitch" to Icons.Filled.Cameraswitch,
    "Campaign" to Icons.Filled.Campaign,
    "Cancel" to Icons.Filled.Cancel,
    "Cancel Presentation" to Icons.Filled.CancelPresentation,
    "Cancel Schedule Send" to Icons.Filled.CancelScheduleSend,
    "Candlestick Chart" to Icons.Filled.CandlestickChart,
    "Car Crash" to Icons.Filled.CarCrash,
    "Car Rental" to Icons.Filled.CarRental,
    "Car Repair" to Icons.Filled.CarRepair,
    "Card Membership" to Icons.Filled.CardMembership,
    "Card Travel" to Icons.Filled.CardTravel,
    "Carpenter" to Icons.Filled.Carpenter,
    "Cases" to Icons.Filled.Cases,
    "Casino" to Icons.Filled.Casino,
    "Cast" to Icons.Filled.Cast,
    "Cast Connected" to Icons.Filled.CastConnected,
    "Cast For Education" to Icons.Filled.CastForEducation,
    "Castle" to Icons.Filled.Castle,
    "Category" to Icons.Filled.Category,
    "Celebration" to Icons.Filled.Celebration,
    "Cell Tower" to Icons.Filled.CellTower,
    "Cell Wifi" to Icons.Filled.CellWifi,
    "Center Focus Strong" to Icons.Filled.CenterFocusStrong,
    "Center Focus Weak" to Icons.Filled.CenterFocusWeak,
    "Chair" to Icons.Filled.Chair,
    "Chair Alt" to Icons.Filled.ChairAlt,
    "Chalet" to Icons.Filled.Chalet,
    "Change Circle" to Icons.Filled.ChangeCircle,
    "Change History" to Icons.Filled.ChangeHistory,
    "Chat" to Icons.Filled.Chat,
    "Chat Bubble" to Icons.Filled.ChatBubble,
    "Check Box" to Icons.Filled.CheckBox,
    "Check Box Outline Blank" to Icons.Filled.CheckBoxOutlineBlank,
    "Checklist" to Icons.Filled.Checklist,
    "Checklist Rtl" to Icons.Filled.ChecklistRtl,
    "Checkroom" to Icons.Filled.Checkroom,
    "Chevron Left" to Icons.Filled.ChevronLeft,
    "Chevron Right" to Icons.Filled.ChevronRight,
    "Child Care" to Icons.Filled.ChildCare,
    "Child Friendly" to Icons.Filled.ChildFriendly,
    "Chrome Reader Mode" to Icons.Filled.ChromeReaderMode,
    "Church" to Icons.Filled.Church,
    "Circle" to Icons.Filled.Circle,
    "Circle Notifications" to Icons.Filled.CircleNotifications,
    "Clean Hands" to Icons.Filled.CleanHands,
    "Cleaning Services" to Icons.Filled.CleaningServices,
    "Clear All" to Icons.Filled.ClearAll,
    "Close Fullscreen" to Icons.Filled.CloseFullscreen,
    "Closed Caption" to Icons.Filled.ClosedCaption,
    "Closed Caption Disabled" to Icons.Filled.ClosedCaptionDisabled,
    "Cloud" to Icons.Filled.Cloud,
    "Cloud Circle" to Icons.Filled.CloudCircle,
    "Cloud Done" to Icons.Filled.CloudDone,
    "Cloud Download" to Icons.Filled.CloudDownload,
    "Cloud Off" to Icons.Filled.CloudOff,
    "Cloud Sync" to Icons.Filled.CloudSync,
    "Cloud Upload" to Icons.Filled.CloudUpload,
    "Co2" to Icons.Filled.Co2,
    "Co Present" to Icons.Filled.CoPresent,
    "Code" to Icons.Filled.Code,
    "Code Off" to Icons.Filled.CodeOff,
    "Coffee" to Icons.Filled.Coffee,
    "Coffee Maker" to Icons.Filled.CoffeeMaker,
    "Collections Bookmark" to Icons.Filled.CollectionsBookmark,
    "Colorize" to Icons.Filled.Colorize,
    "Comment" to Icons.Filled.Comment,
    "Comment Bank" to Icons.Filled.CommentBank,
    "Comments Disabled" to Icons.Filled.CommentsDisabled,
    "Commit" to Icons.Filled.Commit,
    "Commute" to Icons.Filled.Commute,
    "Compare" to Icons.Filled.Compare,
    "Compare Arrows" to Icons.Filled.CompareArrows,
    "Compass Calibration" to Icons.Filled.CompassCalibration,
    "Compost" to Icons.Filled.Compost,
    "Compress" to Icons.Filled.Compress,
    "Computer" to Icons.Filled.Computer,
    "Confirmation Number" to Icons.Filled.ConfirmationNumber,
    "Connect Without Contact" to Icons.Filled.ConnectWithoutContact,
    "Connected Tv" to Icons.Filled.ConnectedTv,
    "Connecting Airports" to Icons.Filled.ConnectingAirports,
    "Construction" to Icons.Filled.Construction,
    "Contact Emergency" to Icons.Filled.ContactEmergency,
    "Contact Mail" to Icons.Filled.ContactMail,
    "Contact Page" to Icons.Filled.ContactPage,
    "Contact Phone" to Icons.Filled.ContactPhone,
    "Contact Support" to Icons.Filled.ContactSupport,
    "Contactless" to Icons.Filled.Contactless,
    "Contacts" to Icons.Filled.Contacts,
    "Content Copy" to Icons.Filled.ContentCopy,
    "Content Cut" to Icons.Filled.ContentCut,
    "Content Paste" to Icons.Filled.ContentPaste,
    "Content Paste Go" to Icons.Filled.ContentPasteGo,
    "Content Paste Off" to Icons.Filled.ContentPasteOff,
    "Content Paste Search" to Icons.Filled.ContentPasteSearch,
    "Contrast" to Icons.Filled.Contrast,
    "Control Camera" to Icons.Filled.ControlCamera,
    "Control Point Duplicate" to Icons.Filled.ControlPointDuplicate,
    "Cookie" to Icons.Filled.Cookie,
    "Copy All" to Icons.Filled.CopyAll,
    "Copyright" to Icons.Filled.Copyright,
    "Coronavirus" to Icons.Filled.Coronavirus,
    "Corporate Fare" to Icons.Filled.CorporateFare,
    "Cottage" to Icons.Filled.Cottage,
    "Countertops" to Icons.Filled.Countertops,
    "Create New Folder" to Icons.Filled.CreateNewFolder,
    "Credit Card" to Icons.Filled.CreditCard,
    "Credit Card Off" to Icons.Filled.CreditCardOff,
    "Credit Score" to Icons.Filled.CreditScore,
    "Crib" to Icons.Filled.Crib,
    "Crisis Alert" to Icons.Filled.CrisisAlert,
    "Crop" to Icons.Filled.Crop,
    "Crop169" to Icons.Filled.Crop169,
    "Crop32" to Icons.Filled.Crop32,
    "Crop54" to Icons.Filled.Crop54,
    "Crop75" to Icons.Filled.Crop75,
    "Crop Free" to Icons.Filled.CropFree,
    "Crop Landscape" to Icons.Filled.CropLandscape,
    "Crop Portrait" to Icons.Filled.CropPortrait,
    "Crop Rotate" to Icons.Filled.CropRotate,
    "Crop Square" to Icons.Filled.CropSquare,
    "Cruelty Free" to Icons.Filled.CrueltyFree,
    "Css" to Icons.Filled.Css,
    "Currency Bitcoin" to Icons.Filled.CurrencyBitcoin,
    "Currency Exchange" to Icons.Filled.CurrencyExchange,
    "Currency Franc" to Icons.Filled.CurrencyFranc,
    "Currency Lira" to Icons.Filled.CurrencyLira,
    "Currency Pound" to Icons.Filled.CurrencyPound,
    "Currency Ruble" to Icons.Filled.CurrencyRuble,
    "Currency Rupee" to Icons.Filled.CurrencyRupee,
    "Currency Yen" to Icons.Filled.CurrencyYen,
    "Currency Yuan" to Icons.Filled.CurrencyYuan,
    "Curtains" to Icons.Filled.Curtains,
    "Curtains Closed" to Icons.Filled.CurtainsClosed,
    "Cyclone" to Icons.Filled.Cyclone,
    "Dangerous" to Icons.Filled.Dangerous,
    "Dark Mode" to Icons.Filled.DarkMode,
    "Dashboard" to Icons.Filled.Dashboard,
    "Dashboard Customize" to Icons.Filled.DashboardCustomize,
    "Data Array" to Icons.Filled.DataArray,
    "Data Exploration" to Icons.Filled.DataExploration,
    "Data Object" to Icons.Filled.DataObject,
    "Data Saver On" to Icons.Filled.DataSaverOn,
    "Data Thresholding" to Icons.Filled.DataThresholding,
    "Data Usage" to Icons.Filled.DataUsage,
    "Dataset" to Icons.Filled.Dataset,
    "Dataset Linked" to Icons.Filled.DatasetLinked,
    "Deblur" to Icons.Filled.Deblur,
    "Deck" to Icons.Filled.Deck,
    "Dehaze" to Icons.Filled.Dehaze,
    "Delete Forever" to Icons.Filled.DeleteForever,
    "Delete Sweep" to Icons.Filled.DeleteSweep,
    "Density Large" to Icons.Filled.DensityLarge,
    "Density Medium" to Icons.Filled.DensityMedium,
    "Density Small" to Icons.Filled.DensitySmall,
    "Departure Board" to Icons.Filled.DepartureBoard,
    "Description" to Icons.Filled.Description,
    "Deselect" to Icons.Filled.Deselect,
    "Design Services" to Icons.Filled.DesignServices,
    "Desk" to Icons.Filled.Desk,
    "Desktop Access Disabled" to Icons.Filled.DesktopAccessDisabled,
    "Desktop Mac" to Icons.Filled.DesktopMac,
    "Desktop Windows" to Icons.Filled.DesktopWindows,
    "Details" to Icons.Filled.Details,
    "Developer Board" to Icons.Filled.DeveloperBoard,
    "Developer Board Off" to Icons.Filled.DeveloperBoardOff,
    "Device Hub" to Icons.Filled.DeviceHub,
    "Device Thermostat" to Icons.Filled.DeviceThermostat,
    "Devices" to Icons.Filled.Devices,
    "Devices Fold" to Icons.Filled.DevicesFold,
    "Devices Other" to Icons.Filled.DevicesOther,
    "Dialer Sip" to Icons.Filled.DialerSip,
    "Dialpad" to Icons.Filled.Dialpad,
    "Diamond" to Icons.Filled.Diamond,
    "Difference" to Icons.Filled.Difference,
    "Dining" to Icons.Filled.Dining,
    "Dinner Dining" to Icons.Filled.DinnerDining,
    "Directions" to Icons.Filled.Directions,
    "Directions Bike" to Icons.Filled.DirectionsBike,
    "Directions Boat" to Icons.Filled.DirectionsBoat,
    "Directions Bus" to Icons.Filled.DirectionsBus,
    "Directions Car" to Icons.Filled.DirectionsCar,
    "Directions Off" to Icons.Filled.DirectionsOff,
    "Directions Railway" to Icons.Filled.DirectionsRailway,
    "Directions Run" to Icons.Filled.DirectionsRun,
    "Directions Subway" to Icons.Filled.DirectionsSubway,
    "Directions Walk" to Icons.Filled.DirectionsWalk,
    "Dirty Lens" to Icons.Filled.DirtyLens,
    "Disabled By Default" to Icons.Filled.DisabledByDefault,
    "Disabled Visible" to Icons.Filled.DisabledVisible,
    "Disc Full" to Icons.Filled.DiscFull,
    "Display Settings" to Icons.Filled.DisplaySettings,
    "Diversity1" to Icons.Filled.Diversity1,
    "Diversity2" to Icons.Filled.Diversity2,
    "Diversity3" to Icons.Filled.Diversity3,
    "Dns" to Icons.Filled.Dns,
    "Do Not Disturb" to Icons.Filled.DoNotDisturb,
    "Do Not Disturb Off" to Icons.Filled.DoNotDisturbOff,
    "Do Not Disturb On" to Icons.Filled.DoNotDisturbOn,
    "Do Not Disturb On Total Silence" to Icons.Filled.DoNotDisturbOnTotalSilence,
    "Do Not Step" to Icons.Filled.DoNotStep,
    "Do Not Touch" to Icons.Filled.DoNotTouch,
    "Dock" to Icons.Filled.Dock,
    "Document Scanner" to Icons.Filled.DocumentScanner,
    "Domain" to Icons.Filled.Domain,
    "Domain Add" to Icons.Filled.DomainAdd,
    "Domain Disabled" to Icons.Filled.DomainDisabled,
    "Domain Verification" to Icons.Filled.DomainVerification,
    "Done All" to Icons.Filled.DoneAll,
    "Done Outline" to Icons.Filled.DoneOutline,
    "Donut Large" to Icons.Filled.DonutLarge,
    "Donut Small" to Icons.Filled.DonutSmall,
    "Door Back" to Icons.Filled.DoorBack,
    "Door Front" to Icons.Filled.DoorFront,
    "Door Sliding" to Icons.Filled.DoorSliding,
    "Doorbell" to Icons.Filled.Doorbell,
    "Double Arrow" to Icons.Filled.DoubleArrow,
    "Downhill Skiing" to Icons.Filled.DownhillSkiing,
    "Download" to Icons.Filled.Download,
    "Download Done" to Icons.Filled.DownloadDone,
    "Download For Offline" to Icons.Filled.DownloadForOffline,
    "Downloading" to Icons.Filled.Downloading,
    "Drafts" to Icons.Filled.Drafts,
    "Drag Handle" to Icons.Filled.DragHandle,
    "Drag Indicator" to Icons.Filled.DragIndicator,
    "Draw" to Icons.Filled.Draw,
    "Drive File Move" to Icons.Filled.DriveFileMove,
    "Drive File Rename Outline" to Icons.Filled.DriveFileRenameOutline,
    "Drive Folder Upload" to Icons.Filled.DriveFolderUpload,
    "Dry" to Icons.Filled.Dry,
    "Dry Cleaning" to Icons.Filled.DryCleaning,
    "Duo" to Icons.Filled.Duo,
    "Dvr" to Icons.Filled.Dvr,
    "Dynamic Feed" to Icons.Filled.DynamicFeed,
    "Dynamic Form" to Icons.Filled.DynamicForm,
    "E Mobiledata" to Icons.Filled.EMobiledata,
    "Earbuds" to Icons.Filled.Earbuds,
    "Earbuds Battery" to Icons.Filled.EarbudsBattery,
    "East" to Icons.Filled.East,
    "Eco" to Icons.Filled.Eco,
    "Edit Attributes" to Icons.Filled.EditAttributes,
    "Edit Calendar" to Icons.Filled.EditCalendar,
    "Edit Location" to Icons.Filled.EditLocation,
    "Edit Location Alt" to Icons.Filled.EditLocationAlt,
    "Edit Note" to Icons.Filled.EditNote,
    "Edit Notifications" to Icons.Filled.EditNotifications,
    "Edit Off" to Icons.Filled.EditOff,
    "Edit Road" to Icons.Filled.EditRoad,
    "Egg" to Icons.Filled.Egg,
    "Egg Alt" to Icons.Filled.EggAlt,
    "Eject" to Icons.Filled.Eject,
    "Elderly" to Icons.Filled.Elderly,
    "Elderly Woman" to Icons.Filled.ElderlyWoman,
    "Electric Bike" to Icons.Filled.ElectricBike,
    "Electric Bolt" to Icons.Filled.ElectricBolt,
    "Electric Car" to Icons.Filled.ElectricCar,
    "Electric Meter" to Icons.Filled.ElectricMeter,
    "Electric Moped" to Icons.Filled.ElectricMoped,
    "Electric Rickshaw" to Icons.Filled.ElectricRickshaw,
    "Electric Scooter" to Icons.Filled.ElectricScooter,
    "Electrical Services" to Icons.Filled.ElectricalServices,
    "Elevator" to Icons.Filled.Elevator,
    "Emergency" to Icons.Filled.Emergency,
    "Emergency Recording" to Icons.Filled.EmergencyRecording,
    "Emergency Share" to Icons.Filled.EmergencyShare,
    "Emoji Food Beverage" to Icons.Filled.EmojiFoodBeverage,
    "Emoji Nature" to Icons.Filled.EmojiNature,
    "Emoji Objects" to Icons.Filled.EmojiObjects,
    "Emoji People" to Icons.Filled.EmojiPeople,
    "Emoji Symbols" to Icons.Filled.EmojiSymbols,
    "Emoji Transportation" to Icons.Filled.EmojiTransportation,
    "Energy Savings Leaf" to Icons.Filled.EnergySavingsLeaf,
    "Engineering" to Icons.Filled.Engineering,
    "Enhanced Encryption" to Icons.Filled.EnhancedEncryption,
    "Equalizer" to Icons.Filled.Equalizer,
    "Error" to Icons.Filled.Error,
    "Escalator" to Icons.Filled.Escalator,
    "Escalator Warning" to Icons.Filled.EscalatorWarning,
    "Euro" to Icons.Filled.Euro,
    "Euro Symbol" to Icons.Filled.EuroSymbol,
    "Ev Station" to Icons.Filled.EvStation,
    "Event" to Icons.Filled.Event,
    "Event Available" to Icons.Filled.EventAvailable,
    "Event Busy" to Icons.Filled.EventBusy,
    "Event Note" to Icons.Filled.EventNote,
    "Event Repeat" to Icons.Filled.EventRepeat,
    "Event Seat" to Icons.Filled.EventSeat,
    "Expand" to Icons.Filled.Expand,
    "Expand Circle Down" to Icons.Filled.ExpandCircleDown,
    "Expand Less" to Icons.Filled.ExpandLess,
    "Expand More" to Icons.Filled.ExpandMore,
    "Explicit" to Icons.Filled.Explicit,
    "Explore" to Icons.Filled.Explore,
    "Explore Off" to Icons.Filled.ExploreOff,
    "Exposure" to Icons.Filled.Exposure,
    "Exposure Neg1" to Icons.Filled.ExposureNeg1,
    "Exposure Neg2" to Icons.Filled.ExposureNeg2,
    "Exposure Plus1" to Icons.Filled.ExposurePlus1,
    "Exposure Plus2" to Icons.Filled.ExposurePlus2,
    "Exposure Zero" to Icons.Filled.ExposureZero,
    "Extension" to Icons.Filled.Extension,
    "Extension Off" to Icons.Filled.ExtensionOff,
    "Face2" to Icons.Filled.Face2,
    "Face3" to Icons.Filled.Face3,
    "Face4" to Icons.Filled.Face4,
    "Face5" to Icons.Filled.Face5,
    "Face6" to Icons.Filled.Face6,
    "Face Retouching Natural" to Icons.Filled.FaceRetouchingNatural,
    "Face Retouching Off" to Icons.Filled.FaceRetouchingOff,
    "Fact Check" to Icons.Filled.FactCheck,
    "Factory" to Icons.Filled.Factory,
    "Family Restroom" to Icons.Filled.FamilyRestroom,
    "Fast Forward" to Icons.Filled.FastForward,
    "Fast Rewind" to Icons.Filled.FastRewind,
    "Fastfood" to Icons.Filled.Fastfood,
    "Fax" to Icons.Filled.Fax,
    "Featured Play List" to Icons.Filled.FeaturedPlayList,
    "Featured Video" to Icons.Filled.FeaturedVideo,
    "Feed" to Icons.Filled.Feed,
    "Female" to Icons.Filled.Female,
    "Fence" to Icons.Filled.Fence,
    "Festival" to Icons.Filled.Festival,
    "Fiber Dvr" to Icons.Filled.FiberDvr,
    "Fiber Manual Record" to Icons.Filled.FiberManualRecord,
    "Fiber New" to Icons.Filled.FiberNew,
    "Fiber Pin" to Icons.Filled.FiberPin,
    "Fiber Smart Record" to Icons.Filled.FiberSmartRecord,
    "File Copy" to Icons.Filled.FileCopy,
    "File Download Off" to Icons.Filled.FileDownloadOff,
    "File Open" to Icons.Filled.FileOpen,
    "File Present" to Icons.Filled.FilePresent,
    "Filter" to Icons.Filled.Filter,
    "Filter1" to Icons.Filled.Filter1,
    "Filter2" to Icons.Filled.Filter2,
    "Filter3" to Icons.Filled.Filter3,
    "Filter4" to Icons.Filled.Filter4,
    "Filter5" to Icons.Filled.Filter5,
    "Filter6" to Icons.Filled.Filter6,
    "Filter7" to Icons.Filled.Filter7,
    "Filter8" to Icons.Filled.Filter8,
    "Filter9" to Icons.Filled.Filter9,
    "Filter9 Plus" to Icons.Filled.Filter9Plus,
    "Filter Alt" to Icons.Filled.FilterAlt,
    "Filter Alt Off" to Icons.Filled.FilterAltOff,
    "Filter B And W" to Icons.Filled.FilterBAndW,
    "Filter Center Focus" to Icons.Filled.FilterCenterFocus,
    "Filter Drama" to Icons.Filled.FilterDrama,
    "Filter Frames" to Icons.Filled.FilterFrames,
    "Filter Hdr" to Icons.Filled.FilterHdr,
    "Filter List" to Icons.Filled.FilterList,
    "Filter List Off" to Icons.Filled.FilterListOff,
    "Filter None" to Icons.Filled.FilterNone,
    "Filter Tilt Shift" to Icons.Filled.FilterTiltShift,
    "Filter Vintage" to Icons.Filled.FilterVintage,
    "Find In Page" to Icons.Filled.FindInPage,
    "Find Replace" to Icons.Filled.FindReplace,
    "Fingerprint" to Icons.Filled.Fingerprint,
    "Fire Extinguisher" to Icons.Filled.FireExtinguisher,
    "Fire Truck" to Icons.Filled.FireTruck,
    "Fireplace" to Icons.Filled.Fireplace,
    "First Page" to Icons.Filled.FirstPage,
    "Fit Screen" to Icons.Filled.FitScreen,
    "Fitness Center" to Icons.Filled.FitnessCenter,
    "Flag" to Icons.Filled.Flag,
    "Flag Circle" to Icons.Filled.FlagCircle,
    "Flaky" to Icons.Filled.Flaky,
    "Flare" to Icons.Filled.Flare,
    "Flash Auto" to Icons.Filled.FlashAuto,
    "Flash Off" to Icons.Filled.FlashOff,
    "Flash On" to Icons.Filled.FlashOn,
    "Flashlight Off" to Icons.Filled.FlashlightOff,
    "Flashlight On" to Icons.Filled.FlashlightOn,
    "Flatware" to Icons.Filled.Flatware,
    "Flight" to Icons.Filled.Flight,
    "Flight Class" to Icons.Filled.FlightClass,
    "Flight Land" to Icons.Filled.FlightLand,
    "Flight Takeoff" to Icons.Filled.FlightTakeoff,
    "Flip" to Icons.Filled.Flip,
    "Flip Camera Android" to Icons.Filled.FlipCameraAndroid,
    "Flip Camera Ios" to Icons.Filled.FlipCameraIos,
    "Flip To Back" to Icons.Filled.FlipToBack,
    "Flip To Front" to Icons.Filled.FlipToFront,
    "Flood" to Icons.Filled.Flood,
    "Flutter Dash" to Icons.Filled.FlutterDash,
    "Fmd Bad" to Icons.Filled.FmdBad,
    "Folder" to Icons.Filled.Folder,
    "Folder Copy" to Icons.Filled.FolderCopy,
    "Folder Delete" to Icons.Filled.FolderDelete,
    "Folder Off" to Icons.Filled.FolderOff,
    "Folder Open" to Icons.Filled.FolderOpen,
    "Folder Shared" to Icons.Filled.FolderShared,
    "Folder Special" to Icons.Filled.FolderSpecial,
    "Folder Zip" to Icons.Filled.FolderZip,
    "Follow The Signs" to Icons.Filled.FollowTheSigns,
    "Font Download" to Icons.Filled.FontDownload,
    "Font Download Off" to Icons.Filled.FontDownloadOff,
    "Food Bank" to Icons.Filled.FoodBank,
    "Forest" to Icons.Filled.Forest,
    "Fork Left" to Icons.Filled.ForkLeft,
    "Fork Right" to Icons.Filled.ForkRight,
    "Format Align Center" to Icons.Filled.FormatAlignCenter,
    "Format Align Justify" to Icons.Filled.FormatAlignJustify,
    "Format Align Left" to Icons.Filled.FormatAlignLeft,
    "Format Align Right" to Icons.Filled.FormatAlignRight,
    "Format Bold" to Icons.Filled.FormatBold,
    "Format Clear" to Icons.Filled.FormatClear,
    "Format Color Fill" to Icons.Filled.FormatColorFill,
    "Format Color Reset" to Icons.Filled.FormatColorReset,
    "Format Color Text" to Icons.Filled.FormatColorText,
    "Format Indent Decrease" to Icons.Filled.FormatIndentDecrease,
    "Format Indent Increase" to Icons.Filled.FormatIndentIncrease,
    "Format Italic" to Icons.Filled.FormatItalic,
    "Format Line Spacing" to Icons.Filled.FormatLineSpacing,
    "Format List Bulleted" to Icons.Filled.FormatListBulleted,
    "Format List Numbered" to Icons.Filled.FormatListNumbered,
    "Format List Numbered Rtl" to Icons.Filled.FormatListNumberedRtl,
    "Format Overline" to Icons.Filled.FormatOverline,
    "Format Paint" to Icons.Filled.FormatPaint,
    "Format Quote" to Icons.Filled.FormatQuote,
    "Format Shapes" to Icons.Filled.FormatShapes,
    "Format Size" to Icons.Filled.FormatSize,
    "Format Strikethrough" to Icons.Filled.FormatStrikethrough,
    "Format Textdirection L To R" to Icons.Filled.FormatTextdirectionLToR,
    "Format Textdirection R To L" to Icons.Filled.FormatTextdirectionRToL,
    "Format Underlined" to Icons.Filled.FormatUnderlined,
    "Fort" to Icons.Filled.Fort,
    "Forum" to Icons.Filled.Forum,
    "Forward" to Icons.Filled.Forward,
    "Forward10" to Icons.Filled.Forward10,
    "Forward30" to Icons.Filled.Forward30,
    "Forward5" to Icons.Filled.Forward5,
    "Forward To Inbox" to Icons.Filled.ForwardToInbox,
    "Foundation" to Icons.Filled.Foundation,
    "Free Cancellation" to Icons.Filled.FreeCancellation,
    "Front Hand" to Icons.Filled.FrontHand,
    "Fullscreen" to Icons.Filled.Fullscreen,
    "Fullscreen Exit" to Icons.Filled.FullscreenExit,
    "Functions" to Icons.Filled.Functions,
    "G Mobiledata" to Icons.Filled.GMobiledata,
    "G Translate" to Icons.Filled.GTranslate,
    "Gamepad" to Icons.Filled.Gamepad,
    "Garage" to Icons.Filled.Garage,
    "Gas Meter" to Icons.Filled.GasMeter,
    "Gavel" to Icons.Filled.Gavel,
    "Generating Tokens" to Icons.Filled.GeneratingTokens,
    "Gesture" to Icons.Filled.Gesture,
    "Gif" to Icons.Filled.Gif,
    "Gif Box" to Icons.Filled.GifBox,
    "Girl" to Icons.Filled.Girl,
    "Gite" to Icons.Filled.Gite,
    "Golf Course" to Icons.Filled.GolfCourse,
    "Gpp Bad" to Icons.Filled.GppBad,
    "Gpp Maybe" to Icons.Filled.GppMaybe,
    "Gradient" to Icons.Filled.Gradient,
    "Grading" to Icons.Filled.Grading,
    "Grain" to Icons.Filled.Grain,
    "Graphic Eq" to Icons.Filled.GraphicEq,
    "Grass" to Icons.Filled.Grass,
    "Grid3x3" to Icons.Filled.Grid3x3,
    "Grid4x4" to Icons.Filled.Grid4x4,
    "Grid Goldenratio" to Icons.Filled.GridGoldenratio,
    "Grid Off" to Icons.Filled.GridOff,
    "Grid On" to Icons.Filled.GridOn,
    "Grid View" to Icons.Filled.GridView,
    "Group" to Icons.Filled.Group,
    "Group Add" to Icons.Filled.GroupAdd,
    "Group Off" to Icons.Filled.GroupOff,
    "Group Remove" to Icons.Filled.GroupRemove,
    "Group Work" to Icons.Filled.GroupWork,
    "Groups" to Icons.Filled.Groups,
    "Groups2" to Icons.Filled.Groups2,
    "Groups3" to Icons.Filled.Groups3,
    "H Mobiledata" to Icons.Filled.HMobiledata,
    "H Plus Mobiledata" to Icons.Filled.HPlusMobiledata,
    "Hail" to Icons.Filled.Hail,
    "Handshake" to Icons.Filled.Handshake,
    "Handyman" to Icons.Filled.Handyman,
    "Hardware" to Icons.Filled.Hardware,
    "Hd" to Icons.Filled.Hd,
    "Hdr Auto" to Icons.Filled.HdrAuto,
    "Hdr Auto Select" to Icons.Filled.HdrAutoSelect,
    "Hdr Enhanced Select" to Icons.Filled.HdrEnhancedSelect,
    "Hdr Off" to Icons.Filled.HdrOff,
    "Hdr Off Select" to Icons.Filled.HdrOffSelect,
    "Hdr On" to Icons.Filled.HdrOn,
    "Hdr On Select" to Icons.Filled.HdrOnSelect,
    "Hdr Plus" to Icons.Filled.HdrPlus,
    "Hdr Strong" to Icons.Filled.HdrStrong,
    "Hdr Weak" to Icons.Filled.HdrWeak,
    "Headphones" to Icons.Filled.Headphones,
    "Headphones Battery" to Icons.Filled.HeadphonesBattery,
    "Headset Mic" to Icons.Filled.HeadsetMic,
    "Headset Off" to Icons.Filled.HeadsetOff,
    "Healing" to Icons.Filled.Healing,
    "Health And Safety" to Icons.Filled.HealthAndSafety,
    "Hearing" to Icons.Filled.Hearing,
    "Hearing Disabled" to Icons.Filled.HearingDisabled,
    "Heart Broken" to Icons.Filled.HeartBroken,
    "Heat Pump" to Icons.Filled.HeatPump,
    "Height" to Icons.Filled.Height,
    "Help" to Icons.Filled.Help,
    "Help Center" to Icons.Filled.HelpCenter,
    "Hevc" to Icons.Filled.Hevc,
    "Hexagon" to Icons.Filled.Hexagon,
    "Hide Image" to Icons.Filled.HideImage,
    "Hide Source" to Icons.Filled.HideSource,
    "High Quality" to Icons.Filled.HighQuality,
    "Highlight" to Icons.Filled.Highlight,
    "Hiking" to Icons.Filled.Hiking,
    "History" to Icons.Filled.History,
    "History Edu" to Icons.Filled.HistoryEdu,
    "History Toggle Off" to Icons.Filled.HistoryToggleOff,
    "Hive" to Icons.Filled.Hive,
    "Hls" to Icons.Filled.Hls,
    "Hls Off" to Icons.Filled.HlsOff,
    "Holiday Village" to Icons.Filled.HolidayVillage,
    "Home Max" to Icons.Filled.HomeMax,
    "Home Mini" to Icons.Filled.HomeMini,
    "Home Repair Service" to Icons.Filled.HomeRepairService,
    "Home Work" to Icons.Filled.HomeWork,
    "Horizontal Distribute" to Icons.Filled.HorizontalDistribute,
    "Horizontal Rule" to Icons.Filled.HorizontalRule,
    "Horizontal Split" to Icons.Filled.HorizontalSplit,
    "Hot Tub" to Icons.Filled.HotTub,
    "Hotel" to Icons.Filled.Hotel,
    "Hotel Class" to Icons.Filled.HotelClass,
    "Hourglass Bottom" to Icons.Filled.HourglassBottom,
    "Hourglass Disabled" to Icons.Filled.HourglassDisabled,
    "Hourglass Empty" to Icons.Filled.HourglassEmpty,
    "Hourglass Full" to Icons.Filled.HourglassFull,
    "Hourglass Top" to Icons.Filled.HourglassTop,
    "House" to Icons.Filled.House,
    "House Siding" to Icons.Filled.HouseSiding,
    "Houseboat" to Icons.Filled.Houseboat,
    "How To Reg" to Icons.Filled.HowToReg,
    "How To Vote" to Icons.Filled.HowToVote,
    "Html" to Icons.Filled.Html,
    "Http" to Icons.Filled.Http,
    "Hub" to Icons.Filled.Hub,
    "Hvac" to Icons.Filled.Hvac,
    "Ice Skating" to Icons.Filled.IceSkating,
    "Icecream" to Icons.Filled.Icecream,
    "Image" to Icons.Filled.Image,
    "Image Aspect Ratio" to Icons.Filled.ImageAspectRatio,
    "Image Not Supported" to Icons.Filled.ImageNotSupported,
    "Image Search" to Icons.Filled.ImageSearch,
    "Imagesearch Roller" to Icons.Filled.ImagesearchRoller,
    "Import Contacts" to Icons.Filled.ImportContacts,
    "Important Devices" to Icons.Filled.ImportantDevices,
    "Inbox" to Icons.Filled.Inbox,
    "Incomplete Circle" to Icons.Filled.IncompleteCircle,
    "Indeterminate Check Box" to Icons.Filled.IndeterminateCheckBox,
    "Input" to Icons.Filled.Input,
    "Insert Chart" to Icons.Filled.InsertChart,
    "Insert Page Break" to Icons.Filled.InsertPageBreak,
    "Insights" to Icons.Filled.Insights,
    "Install Desktop" to Icons.Filled.InstallDesktop,
    "Integration Instructions" to Icons.Filled.IntegrationInstructions,
    "Interests" to Icons.Filled.Interests,
    "Interpreter Mode" to Icons.Filled.InterpreterMode,
    "Inventory" to Icons.Filled.Inventory,
    "Inventory2" to Icons.Filled.Inventory2,
    "Invert Colors" to Icons.Filled.InvertColors,
    "Invert Colors Off" to Icons.Filled.InvertColorsOff,
    "Ios Share" to Icons.Filled.IosShare,
    "Iron" to Icons.Filled.Iron,
    "Javascript" to Icons.Filled.Javascript,
    "Join Inner" to Icons.Filled.JoinInner,
    "Join Left" to Icons.Filled.JoinLeft,
    "Join Right" to Icons.Filled.JoinRight,
    "Kayaking" to Icons.Filled.Kayaking,
    "Kebab Dining" to Icons.Filled.KebabDining,
    "Key" to Icons.Filled.Key,
    "Key Off" to Icons.Filled.KeyOff,
    "Keyboard" to Icons.Filled.Keyboard,
    "Keyboard Alt" to Icons.Filled.KeyboardAlt,
    "Keyboard Backspace" to Icons.Filled.KeyboardBackspace,
    "Keyboard Capslock" to Icons.Filled.KeyboardCapslock,
    "Keyboard Command Key" to Icons.Filled.KeyboardCommandKey,
    "Keyboard Control Key" to Icons.Filled.KeyboardControlKey,
    "Keyboard Double Arrow Down" to Icons.Filled.KeyboardDoubleArrowDown,
    "Keyboard Double Arrow Left" to Icons.Filled.KeyboardDoubleArrowLeft,
    "Keyboard Double Arrow Right" to Icons.Filled.KeyboardDoubleArrowRight,
    "Keyboard Double Arrow Up" to Icons.Filled.KeyboardDoubleArrowUp,
    "Keyboard Hide" to Icons.Filled.KeyboardHide,
    "Keyboard Option Key" to Icons.Filled.KeyboardOptionKey,
    "Keyboard Return" to Icons.Filled.KeyboardReturn,
    "Keyboard Tab" to Icons.Filled.KeyboardTab,
    "King Bed" to Icons.Filled.KingBed,
    "Kitchen" to Icons.Filled.Kitchen,
    "Kitesurfing" to Icons.Filled.Kitesurfing,
    "Label" to Icons.Filled.Label,
    "Label Important" to Icons.Filled.LabelImportant,
    "Label Off" to Icons.Filled.LabelOff,
    "Lan" to Icons.Filled.Lan,
    "Landscape" to Icons.Filled.Landscape,
    "Landslide" to Icons.Filled.Landslide,
    "Language" to Icons.Filled.Language,
    "Laptop Chromebook" to Icons.Filled.LaptopChromebook,
    "Laptop Mac" to Icons.Filled.LaptopMac,
    "Laptop Windows" to Icons.Filled.LaptopWindows,
    "Last Page" to Icons.Filled.LastPage,
    "Layers" to Icons.Filled.Layers,
    "Layers Clear" to Icons.Filled.LayersClear,
    "Leaderboard" to Icons.Filled.Leaderboard,
    "Leak Add" to Icons.Filled.LeakAdd,
    "Leak Remove" to Icons.Filled.LeakRemove,
    "Legend Toggle" to Icons.Filled.LegendToggle,
    "Lens Blur" to Icons.Filled.LensBlur,
    "Library Add" to Icons.Filled.LibraryAdd,
    "Library Add Check" to Icons.Filled.LibraryAddCheck,
    "Library Books" to Icons.Filled.LibraryBooks,
    "Library Music" to Icons.Filled.LibraryMusic,
    "Light" to Icons.Filled.Light,
    "Light Mode" to Icons.Filled.LightMode,
    "Lightbulb" to Icons.Filled.Lightbulb,
    "Lightbulb Circle" to Icons.Filled.LightbulbCircle,
    "Line Axis" to Icons.Filled.LineAxis,
    "Line Style" to Icons.Filled.LineStyle,
    "Line Weight" to Icons.Filled.LineWeight,
    "Linear Scale" to Icons.Filled.LinearScale,
    "Link" to Icons.Filled.Link,
    "Link Off" to Icons.Filled.LinkOff,
    "Linked Camera" to Icons.Filled.LinkedCamera,
    "Liquor" to Icons.Filled.Liquor,
    "List Alt" to Icons.Filled.ListAlt,
    "Live Help" to Icons.Filled.LiveHelp,
    "Live Tv" to Icons.Filled.LiveTv,
    "Living" to Icons.Filled.Living,
    "Local Activity" to Icons.Filled.LocalActivity,
    "Local Atm" to Icons.Filled.LocalAtm,
    "Local Bar" to Icons.Filled.LocalBar,
    "Local Cafe" to Icons.Filled.LocalCafe,
    "Local Car Wash" to Icons.Filled.LocalCarWash,
    "Local Convenience Store" to Icons.Filled.LocalConvenienceStore,
    "Local Drink" to Icons.Filled.LocalDrink,
    "Local Fire Department" to Icons.Filled.LocalFireDepartment,
    "Local Florist" to Icons.Filled.LocalFlorist,
    "Local Gas Station" to Icons.Filled.LocalGasStation,
    "Local Hospital" to Icons.Filled.LocalHospital,
    "Local Laundry Service" to Icons.Filled.LocalLaundryService,
    "Local Library" to Icons.Filled.LocalLibrary,
    "Local Mall" to Icons.Filled.LocalMall,
    "Local Parking" to Icons.Filled.LocalParking,
    "Local Pharmacy" to Icons.Filled.LocalPharmacy,
    "Local Pizza" to Icons.Filled.LocalPizza,
    "Local Police" to Icons.Filled.LocalPolice,
    "Local Post Office" to Icons.Filled.LocalPostOffice,
    "Local See" to Icons.Filled.LocalSee,
    "Local Shipping" to Icons.Filled.LocalShipping,
    "Local Taxi" to Icons.Filled.LocalTaxi,
    "Location City" to Icons.Filled.LocationCity,
    "Location Disabled" to Icons.Filled.LocationDisabled,
    "Location Off" to Icons.Filled.LocationOff,
    "Location Searching" to Icons.Filled.LocationSearching,
    "Lock Clock" to Icons.Filled.LockClock,
    "Lock Open" to Icons.Filled.LockOpen,
    "Lock Person" to Icons.Filled.LockPerson,
    "Lock Reset" to Icons.Filled.LockReset,
    "Login" to Icons.Filled.Login,
    "Logo Dev" to Icons.Filled.LogoDev,
    "Logout" to Icons.Filled.Logout,
    "Looks" to Icons.Filled.Looks,
    "Looks3" to Icons.Filled.Looks3,
    "Looks4" to Icons.Filled.Looks4,
    "Looks5" to Icons.Filled.Looks5,
    "Looks6" to Icons.Filled.Looks6,
    "Looks One" to Icons.Filled.LooksOne,
    "Looks Two" to Icons.Filled.LooksTwo,
    "Loupe" to Icons.Filled.Loupe,
    "Low Priority" to Icons.Filled.LowPriority,
    "Loyalty" to Icons.Filled.Loyalty,
    "Lte Mobiledata" to Icons.Filled.LteMobiledata,
    "Lte Plus Mobiledata" to Icons.Filled.LtePlusMobiledata,
    "Luggage" to Icons.Filled.Luggage,
    "Lunch Dining" to Icons.Filled.LunchDining,
    "Lyrics" to Icons.Filled.Lyrics,
    "Macro Off" to Icons.Filled.MacroOff,
    "Mail" to Icons.Filled.Mail,
    "Mail Lock" to Icons.Filled.MailLock,
    "Male" to Icons.Filled.Male,
    "Man" to Icons.Filled.Man,
    "Man2" to Icons.Filled.Man2,
    "Man3" to Icons.Filled.Man3,
    "Man4" to Icons.Filled.Man4,
    "Manage Accounts" to Icons.Filled.ManageAccounts,
    "Manage History" to Icons.Filled.ManageHistory,
    "Manage Search" to Icons.Filled.ManageSearch,
    "Map" to Icons.Filled.Map,
    "Maps Ugc" to Icons.Filled.MapsUgc,
    "Margin" to Icons.Filled.Margin,
    "Mark As Unread" to Icons.Filled.MarkAsUnread,
    "Mark Chat Read" to Icons.Filled.MarkChatRead,
    "Mark Chat Unread" to Icons.Filled.MarkChatUnread,
    "Mark Email Read" to Icons.Filled.MarkEmailRead,
    "Mark Email Unread" to Icons.Filled.MarkEmailUnread,
    "Mark Unread Chat Alt" to Icons.Filled.MarkUnreadChatAlt,
    "Markunread Mailbox" to Icons.Filled.MarkunreadMailbox,
    "Masks" to Icons.Filled.Masks,
    "Maximize" to Icons.Filled.Maximize,
    "Media Bluetooth Off" to Icons.Filled.MediaBluetoothOff,
    "Media Bluetooth On" to Icons.Filled.MediaBluetoothOn,
    "Mediation" to Icons.Filled.Mediation,
    "Medical Information" to Icons.Filled.MedicalInformation,
    "Medical Services" to Icons.Filled.MedicalServices,
    "Medication" to Icons.Filled.Medication,
    "Meeting Room" to Icons.Filled.MeetingRoom,
    "Memory" to Icons.Filled.Memory,
    "Menu Book" to Icons.Filled.MenuBook,
    "Menu Open" to Icons.Filled.MenuOpen,
    "Merge" to Icons.Filled.Merge,
    "Merge Type" to Icons.Filled.MergeType,
    "Mic" to Icons.Filled.Mic,
    "Mic External Off" to Icons.Filled.MicExternalOff,
    "Mic External On" to Icons.Filled.MicExternalOn,
    "Mic Off" to Icons.Filled.MicOff,
    "Microwave" to Icons.Filled.Microwave,
    "Military Tech" to Icons.Filled.MilitaryTech,
    "Minimize" to Icons.Filled.Minimize,
    "Minor Crash" to Icons.Filled.MinorCrash,
    "Missed Video Call" to Icons.Filled.MissedVideoCall,
    "Mms" to Icons.Filled.Mms,
    "Mobile Off" to Icons.Filled.MobileOff,
    "Mobiledata Off" to Icons.Filled.MobiledataOff,
    "Mode Comment" to Icons.Filled.ModeComment,
    "Mode Fan Off" to Icons.Filled.ModeFanOff,
    "Mode Of Travel" to Icons.Filled.ModeOfTravel,
    "Mode Standby" to Icons.Filled.ModeStandby,
    "Model Training" to Icons.Filled.ModelTraining,
    "Monetization On" to Icons.Filled.MonetizationOn,
    "Money" to Icons.Filled.Money,
    "Money Off" to Icons.Filled.MoneyOff,
    "Monitor" to Icons.Filled.Monitor,
    "Monitor Heart" to Icons.Filled.MonitorHeart,
    "Monitor Weight" to Icons.Filled.MonitorWeight,
    "Monochrome Photos" to Icons.Filled.MonochromePhotos,
    "Mood" to Icons.Filled.Mood,
    "Mood Bad" to Icons.Filled.MoodBad,
    "Moped" to Icons.Filled.Moped,
    "More" to Icons.Filled.More,
    "More Horiz" to Icons.Filled.MoreHoriz,
    "More Time" to Icons.Filled.MoreTime,
    "Mosque" to Icons.Filled.Mosque,
    "Motion Photos Auto" to Icons.Filled.MotionPhotosAuto,
    "Motion Photos Off" to Icons.Filled.MotionPhotosOff,
    "Motion Photos On" to Icons.Filled.MotionPhotosOn,
    "Motion Photos Paused" to Icons.Filled.MotionPhotosPaused,
    "Motorcycle" to Icons.Filled.Motorcycle,
    "Mouse" to Icons.Filled.Mouse,
    "Move Down" to Icons.Filled.MoveDown,
    "Move To Inbox" to Icons.Filled.MoveToInbox,
    "Move Up" to Icons.Filled.MoveUp,
    "Movie" to Icons.Filled.Movie,
    "Movie Filter" to Icons.Filled.MovieFilter,
    "Moving" to Icons.Filled.Moving,
    "Mp" to Icons.Filled.Mp,
    "Multiline Chart" to Icons.Filled.MultilineChart,
    "Multiple Stop" to Icons.Filled.MultipleStop,
    "Museum" to Icons.Filled.Museum,
    "Music Note" to Icons.Filled.MusicNote,
    "Music Off" to Icons.Filled.MusicOff,
    "Music Video" to Icons.Filled.MusicVideo,
    "My Location" to Icons.Filled.MyLocation,
    "Nat" to Icons.Filled.Nat,
    "Nature" to Icons.Filled.Nature,
    "Nature People" to Icons.Filled.NaturePeople,
    "Navigation" to Icons.Filled.Navigation,
    "Near Me" to Icons.Filled.NearMe,
    "Near Me Disabled" to Icons.Filled.NearMeDisabled,
    "Nearby Error" to Icons.Filled.NearbyError,
    "Nearby Off" to Icons.Filled.NearbyOff,
    "Nest Cam Wired Stand" to Icons.Filled.NestCamWiredStand,
    "Network Cell" to Icons.Filled.NetworkCell,
    "Network Check" to Icons.Filled.NetworkCheck,
    "Network Locked" to Icons.Filled.NetworkLocked,
    "Network Ping" to Icons.Filled.NetworkPing,
    "Network Wifi" to Icons.Filled.NetworkWifi,
    "Network Wifi1 Bar" to Icons.Filled.NetworkWifi1Bar,
    "Network Wifi2 Bar" to Icons.Filled.NetworkWifi2Bar,
    "Network Wifi3 Bar" to Icons.Filled.NetworkWifi3Bar,
    "New Label" to Icons.Filled.NewLabel,
    "Newspaper" to Icons.Filled.Newspaper,
    "Next Plan" to Icons.Filled.NextPlan,
    "Next Week" to Icons.Filled.NextWeek,
    "Nfc" to Icons.Filled.Nfc,
    "Night Shelter" to Icons.Filled.NightShelter,
    "Nightlife" to Icons.Filled.Nightlife,
    "Nightlight" to Icons.Filled.Nightlight,
    "No Accounts" to Icons.Filled.NoAccounts,
    "No Adult Content" to Icons.Filled.NoAdultContent,
    "No Backpack" to Icons.Filled.NoBackpack,
    "No Crash" to Icons.Filled.NoCrash,
    "No Drinks" to Icons.Filled.NoDrinks,
    "No Encryption" to Icons.Filled.NoEncryption,
    "No Flash" to Icons.Filled.NoFlash,
    "No Food" to Icons.Filled.NoFood,
    "No Luggage" to Icons.Filled.NoLuggage,
    "No Meals" to Icons.Filled.NoMeals,
    "No Meeting Room" to Icons.Filled.NoMeetingRoom,
    "No Photography" to Icons.Filled.NoPhotography,
    "No Sim" to Icons.Filled.NoSim,
    "No Stroller" to Icons.Filled.NoStroller,
    "No Transfer" to Icons.Filled.NoTransfer,
    "Noise Aware" to Icons.Filled.NoiseAware,
    "Noise Control Off" to Icons.Filled.NoiseControlOff,
    "Nordic Walking" to Icons.Filled.NordicWalking,
    "North" to Icons.Filled.North,
    "North East" to Icons.Filled.NorthEast,
    "North West" to Icons.Filled.NorthWest,
    "Not Accessible" to Icons.Filled.NotAccessible,
    "Not Listed Location" to Icons.Filled.NotListedLocation,
    "Not Started" to Icons.Filled.NotStarted,
    "Note" to Icons.Filled.Note,
    "Note Add" to Icons.Filled.NoteAdd,
    "Note Alt" to Icons.Filled.NoteAlt,
    "Notes" to Icons.Filled.Notes,
    "Notification Add" to Icons.Filled.NotificationAdd,
    "Notification Important" to Icons.Filled.NotificationImportant,
    "Notifications Active" to Icons.Filled.NotificationsActive,
    "Notifications Off" to Icons.Filled.NotificationsOff,
    "Notifications Paused" to Icons.Filled.NotificationsPaused,
    "Numbers" to Icons.Filled.Numbers,
    "Offline Bolt" to Icons.Filled.OfflineBolt,
    "Offline Pin" to Icons.Filled.OfflinePin,
    "Oil Barrel" to Icons.Filled.OilBarrel,
    "On Device Training" to Icons.Filled.OnDeviceTraining,
    "Online Prediction" to Icons.Filled.OnlinePrediction,
    "Opacity" to Icons.Filled.Opacity,
    "Open In Browser" to Icons.Filled.OpenInBrowser,
    "Open In Full" to Icons.Filled.OpenInFull,
    "Open In New" to Icons.Filled.OpenInNew,
    "Open In New Off" to Icons.Filled.OpenInNewOff,
    "Open With" to Icons.Filled.OpenWith,
    "Other Houses" to Icons.Filled.OtherHouses,
    "Outbound" to Icons.Filled.Outbound,
    "Outbox" to Icons.Filled.Outbox,
    "Outdoor Grill" to Icons.Filled.OutdoorGrill,
    "Outlet" to Icons.Filled.Outlet,
    "Output" to Icons.Filled.Output,
    "Padding" to Icons.Filled.Padding,
    "Pages" to Icons.Filled.Pages,
    "Pageview" to Icons.Filled.Pageview,
    "Paid" to Icons.Filled.Paid,
    "Palette" to Icons.Filled.Palette,
    "Pan Tool" to Icons.Filled.PanTool,
    "Pan Tool Alt" to Icons.Filled.PanToolAlt,
    "Panorama" to Icons.Filled.Panorama,
    "Panorama Fish Eye" to Icons.Filled.PanoramaFishEye,
    "Panorama Horizontal" to Icons.Filled.PanoramaHorizontal,
    "Panorama Photosphere" to Icons.Filled.PanoramaPhotosphere,
    "Panorama Vertical" to Icons.Filled.PanoramaVertical,
    "Panorama Wide Angle" to Icons.Filled.PanoramaWideAngle,
    "Paragliding" to Icons.Filled.Paragliding,
    "Park" to Icons.Filled.Park,
    "Party Mode" to Icons.Filled.PartyMode,
    "Password" to Icons.Filled.Password,
    "Pattern" to Icons.Filled.Pattern,
    "Pause" to Icons.Filled.Pause,
    "Pause Circle" to Icons.Filled.PauseCircle,
    "Pause Presentation" to Icons.Filled.PausePresentation,
    "Payments" to Icons.Filled.Payments,
    "Pedal Bike" to Icons.Filled.PedalBike,
    "Pending" to Icons.Filled.Pending,
    "Pending Actions" to Icons.Filled.PendingActions,
    "Pentagon" to Icons.Filled.Pentagon,
    "Percent" to Icons.Filled.Percent,
    "Perm Camera Mic" to Icons.Filled.PermCameraMic,
    "Perm Contact Calendar" to Icons.Filled.PermContactCalendar,
    "Perm Data Setting" to Icons.Filled.PermDataSetting,
    "Perm Media" to Icons.Filled.PermMedia,
    "Perm Phone Msg" to Icons.Filled.PermPhoneMsg,
    "Perm Scan Wifi" to Icons.Filled.PermScanWifi,
    "Person2" to Icons.Filled.Person2,
    "Person3" to Icons.Filled.Person3,
    "Person4" to Icons.Filled.Person4,
    "Person Add" to Icons.Filled.PersonAdd,
    "Person Add Disabled" to Icons.Filled.PersonAddDisabled,
    "Person Off" to Icons.Filled.PersonOff,
    "Person Pin" to Icons.Filled.PersonPin,
    "Person Pin Circle" to Icons.Filled.PersonPinCircle,
    "Person Remove" to Icons.Filled.PersonRemove,
    "Person Search" to Icons.Filled.PersonSearch,
    "Personal Injury" to Icons.Filled.PersonalInjury,
    "Pest Control" to Icons.Filled.PestControl,
    "Pest Control Rodent" to Icons.Filled.PestControlRodent,
    "Pets" to Icons.Filled.Pets,
    "Phishing" to Icons.Filled.Phishing,
    "Phone Bluetooth Speaker" to Icons.Filled.PhoneBluetoothSpeaker,
    "Phone Callback" to Icons.Filled.PhoneCallback,
    "Phone Disabled" to Icons.Filled.PhoneDisabled,
    "Phone Enabled" to Icons.Filled.PhoneEnabled,
    "Phone Forwarded" to Icons.Filled.PhoneForwarded,
    "Phone In Talk" to Icons.Filled.PhoneInTalk,
    "Phone Locked" to Icons.Filled.PhoneLocked,
    "Phone Missed" to Icons.Filled.PhoneMissed,
    "Phone Paused" to Icons.Filled.PhonePaused,
    "Photo" to Icons.Filled.Photo,
    "Photo Album" to Icons.Filled.PhotoAlbum,
    "Photo Camera" to Icons.Filled.PhotoCamera,
    "Photo Camera Back" to Icons.Filled.PhotoCameraBack,
    "Photo Camera Front" to Icons.Filled.PhotoCameraFront,
    "Photo Filter" to Icons.Filled.PhotoFilter,
    "Photo Library" to Icons.Filled.PhotoLibrary,
    "Photo Size Select Large" to Icons.Filled.PhotoSizeSelectLarge,
    "Photo Size Select Small" to Icons.Filled.PhotoSizeSelectSmall,
    "Php" to Icons.Filled.Php,
    "Piano" to Icons.Filled.Piano,
    "Piano Off" to Icons.Filled.PianoOff,
    "Picture As Pdf" to Icons.Filled.PictureAsPdf,
    "Picture In Picture" to Icons.Filled.PictureInPicture,
    "Picture In Picture Alt" to Icons.Filled.PictureInPictureAlt,
    "Pie Chart" to Icons.Filled.PieChart,
    "Pin" to Icons.Filled.Pin,
    "Pin Drop" to Icons.Filled.PinDrop,
    "Pin End" to Icons.Filled.PinEnd,
    "Pin Invoke" to Icons.Filled.PinInvoke,
    "Pinch" to Icons.Filled.Pinch,
    "Pivot Table Chart" to Icons.Filled.PivotTableChart,
    "Plagiarism" to Icons.Filled.Plagiarism,
    "Play Circle" to Icons.Filled.PlayCircle,
    "Play Disabled" to Icons.Filled.PlayDisabled,
    "Play For Work" to Icons.Filled.PlayForWork,
    "Play Lesson" to Icons.Filled.PlayLesson,
    "Playlist Add" to Icons.Filled.PlaylistAdd,
    "Playlist Add Check" to Icons.Filled.PlaylistAddCheck,
    "Playlist Add Check Circle" to Icons.Filled.PlaylistAddCheckCircle,
    "Playlist Add Circle" to Icons.Filled.PlaylistAddCircle,
    "Playlist Play" to Icons.Filled.PlaylistPlay,
    "Playlist Remove" to Icons.Filled.PlaylistRemove,
    "Plumbing" to Icons.Filled.Plumbing,
    "Podcasts" to Icons.Filled.Podcasts,
    "Point Of Sale" to Icons.Filled.PointOfSale,
    "Policy" to Icons.Filled.Policy,
    "Polyline" to Icons.Filled.Polyline,
    "Polymer" to Icons.Filled.Polymer,
    "Pool" to Icons.Filled.Pool,
    "Post Add" to Icons.Filled.PostAdd,
    "Power" to Icons.Filled.Power,
    "Power Input" to Icons.Filled.PowerInput,
    "Power Off" to Icons.Filled.PowerOff,
    "Power Settings New" to Icons.Filled.PowerSettingsNew,
    "Precision Manufacturing" to Icons.Filled.PrecisionManufacturing,
    "Present To All" to Icons.Filled.PresentToAll,
    "Preview" to Icons.Filled.Preview,
    "Price Change" to Icons.Filled.PriceChange,
    "Price Check" to Icons.Filled.PriceCheck,
    "Print" to Icons.Filled.Print,
    "Print Disabled" to Icons.Filled.PrintDisabled,
    "Priority High" to Icons.Filled.PriorityHigh,
    "Privacy Tip" to Icons.Filled.PrivacyTip,
    "Private Connectivity" to Icons.Filled.PrivateConnectivity,
    "Production Quantity Limits" to Icons.Filled.ProductionQuantityLimits,
    "Propane" to Icons.Filled.Propane,
    "Propane Tank" to Icons.Filled.PropaneTank,
    "Psychology" to Icons.Filled.Psychology,
    "Psychology Alt" to Icons.Filled.PsychologyAlt,
    "Public" to Icons.Filled.Public,
    "Public Off" to Icons.Filled.PublicOff,
    "Publish" to Icons.Filled.Publish,
    "Published With Changes" to Icons.Filled.PublishedWithChanges,
    "Punch Clock" to Icons.Filled.PunchClock,
    "Push Pin" to Icons.Filled.PushPin,
    "Qr Code" to Icons.Filled.QrCode,
    "Qr Code2" to Icons.Filled.QrCode2,
    "Qr Code Scanner" to Icons.Filled.QrCodeScanner,
    "Query Stats" to Icons.Filled.QueryStats,
    "Question Mark" to Icons.Filled.QuestionMark,
    "Queue Music" to Icons.Filled.QueueMusic,
    "Queue Play Next" to Icons.Filled.QueuePlayNext,
    "Quickreply" to Icons.Filled.Quickreply,
    "Quiz" to Icons.Filled.Quiz,
    "R Mobiledata" to Icons.Filled.RMobiledata,
    "Radar" to Icons.Filled.Radar,
    "Radio" to Icons.Filled.Radio,
    "Radio Button Checked" to Icons.Filled.RadioButtonChecked,
    "Radio Button Unchecked" to Icons.Filled.RadioButtonUnchecked,
    "Railway Alert" to Icons.Filled.RailwayAlert,
    "Ramen Dining" to Icons.Filled.RamenDining,
    "Ramp Left" to Icons.Filled.RampLeft,
    "Ramp Right" to Icons.Filled.RampRight,
    "Rate Review" to Icons.Filled.RateReview,
    "Raw Off" to Icons.Filled.RawOff,
    "Raw On" to Icons.Filled.RawOn,
    "Read More" to Icons.Filled.ReadMore,
    "Real Estate Agent" to Icons.Filled.RealEstateAgent,
    "Receipt" to Icons.Filled.Receipt,
    "Receipt Long" to Icons.Filled.ReceiptLong,
    "Recent Actors" to Icons.Filled.RecentActors,
    "Recommend" to Icons.Filled.Recommend,
    "Record Voice Over" to Icons.Filled.RecordVoiceOver,
    "Rectangle" to Icons.Filled.Rectangle,
    "Recycling" to Icons.Filled.Recycling,
    "Redeem" to Icons.Filled.Redeem,
    "Redo" to Icons.Filled.Redo,
    "Reduce Capacity" to Icons.Filled.ReduceCapacity,
    "Remember Me" to Icons.Filled.RememberMe,
    "Remove" to Icons.Filled.Remove,
    "Remove Done" to Icons.Filled.RemoveDone,
    "Remove From Queue" to Icons.Filled.RemoveFromQueue,
    "Remove Moderator" to Icons.Filled.RemoveModerator,
    "Remove Road" to Icons.Filled.RemoveRoad,
    "Remove Shopping Cart" to Icons.Filled.RemoveShoppingCart,
    "Reorder" to Icons.Filled.Reorder,
    "Repartition" to Icons.Filled.Repartition,
    "Repeat" to Icons.Filled.Repeat,
    "Repeat On" to Icons.Filled.RepeatOn,
    "Repeat One" to Icons.Filled.RepeatOne,
    "Repeat One On" to Icons.Filled.RepeatOneOn,
    "Replay" to Icons.Filled.Replay,
    "Replay10" to Icons.Filled.Replay10,
    "Replay30" to Icons.Filled.Replay30,
    "Replay5" to Icons.Filled.Replay5,
    "Replay Circle Filled" to Icons.Filled.ReplayCircleFilled,
    "Reply" to Icons.Filled.Reply,
    "Reply All" to Icons.Filled.ReplyAll,
    "Report" to Icons.Filled.Report,
    "Report Off" to Icons.Filled.ReportOff,
    "Request Page" to Icons.Filled.RequestPage,
    "Request Quote" to Icons.Filled.RequestQuote,
    "Reset Tv" to Icons.Filled.ResetTv,
    "Restart Alt" to Icons.Filled.RestartAlt,
    "Restaurant" to Icons.Filled.Restaurant,
    "Restaurant Menu" to Icons.Filled.RestaurantMenu,
    "Restore From Trash" to Icons.Filled.RestoreFromTrash,
    "Restore Page" to Icons.Filled.RestorePage,
    "Reviews" to Icons.Filled.Reviews,
    "Rice Bowl" to Icons.Filled.RiceBowl,
    "Ring Volume" to Icons.Filled.RingVolume,
    "Rocket" to Icons.Filled.Rocket,
    "Rocket Launch" to Icons.Filled.RocketLaunch,
    "Roller Shades" to Icons.Filled.RollerShades,
    "Roller Shades Closed" to Icons.Filled.RollerShadesClosed,
    "Roller Skating" to Icons.Filled.RollerSkating,
    "Roofing" to Icons.Filled.Roofing,
    "Room Preferences" to Icons.Filled.RoomPreferences,
    "Room Service" to Icons.Filled.RoomService,
    "Rotate90 Degrees Ccw" to Icons.Filled.Rotate90DegreesCcw,
    "Rotate90 Degrees Cw" to Icons.Filled.Rotate90DegreesCw,
    "Rotate Left" to Icons.Filled.RotateLeft,
    "Rotate Right" to Icons.Filled.RotateRight,
    "Roundabout Left" to Icons.Filled.RoundaboutLeft,
    "Roundabout Right" to Icons.Filled.RoundaboutRight,
    "Rounded Corner" to Icons.Filled.RoundedCorner,
    "Route" to Icons.Filled.Route,
    "Router" to Icons.Filled.Router,
    "Rowing" to Icons.Filled.Rowing,
    "Rss Feed" to Icons.Filled.RssFeed,
    "Rsvp" to Icons.Filled.Rsvp,
    "Rtt" to Icons.Filled.Rtt,
    "Rule" to Icons.Filled.Rule,
    "Rule Folder" to Icons.Filled.RuleFolder,
    "Run Circle" to Icons.Filled.RunCircle,
    "Running With Errors" to Icons.Filled.RunningWithErrors,
    "Rv Hookup" to Icons.Filled.RvHookup,
    "Safety Check" to Icons.Filled.SafetyCheck,
    "Safety Divider" to Icons.Filled.SafetyDivider,
    "Sailing" to Icons.Filled.Sailing,
    "Sanitizer" to Icons.Filled.Sanitizer,
    "Satellite" to Icons.Filled.Satellite,
    "Satellite Alt" to Icons.Filled.SatelliteAlt,
    "Save" to Icons.Filled.Save,
    "Save As" to Icons.Filled.SaveAs,
    "Saved Search" to Icons.Filled.SavedSearch,
    "Savings" to Icons.Filled.Savings,
    "Scale" to Icons.Filled.Scale,
    "Scanner" to Icons.Filled.Scanner,
    "Scatter Plot" to Icons.Filled.ScatterPlot,
    "Schedule" to Icons.Filled.Schedule,
    "Schedule Send" to Icons.Filled.ScheduleSend,
    "Schema" to Icons.Filled.Schema,
    "School" to Icons.Filled.School,
    "Science" to Icons.Filled.Science,
    "Score" to Icons.Filled.Score,
    "Scoreboard" to Icons.Filled.Scoreboard,
    "Screen Rotation Alt" to Icons.Filled.ScreenRotationAlt,
    "Screen Search Desktop" to Icons.Filled.ScreenSearchDesktop,
    "Screen Share" to Icons.Filled.ScreenShare,
    "Screenshot" to Icons.Filled.Screenshot,
    "Screenshot Monitor" to Icons.Filled.ScreenshotMonitor,
    "Scuba Diving" to Icons.Filled.ScubaDiving,
    "Sd" to Icons.Filled.Sd,
    "Sd Card" to Icons.Filled.SdCard,
    "Sd Card Alert" to Icons.Filled.SdCardAlert,
    "Search Off" to Icons.Filled.SearchOff,
    "Security" to Icons.Filled.Security,
    "Segment" to Icons.Filled.Segment,
    "Select All" to Icons.Filled.SelectAll,
    "Self Improvement" to Icons.Filled.SelfImprovement,
    "Sell" to Icons.Filled.Sell,
    "Send And Archive" to Icons.Filled.SendAndArchive,
    "Send Time Extension" to Icons.Filled.SendTimeExtension,
    "Sensor Door" to Icons.Filled.SensorDoor,
    "Sensor Occupied" to Icons.Filled.SensorOccupied,
    "Sensor Window" to Icons.Filled.SensorWindow,
    "Sensors" to Icons.Filled.Sensors,
    "Sensors Off" to Icons.Filled.SensorsOff,
    "Sentiment Dissatisfied" to Icons.Filled.SentimentDissatisfied,
    "Sentiment Neutral" to Icons.Filled.SentimentNeutral,
    "Sentiment Satisfied" to Icons.Filled.SentimentSatisfied,
    "Sentiment Very Dissatisfied" to Icons.Filled.SentimentVeryDissatisfied,
    "Sentiment Very Satisfied" to Icons.Filled.SentimentVerySatisfied,
    "Set Meal" to Icons.Filled.SetMeal,
    "Settings Accessibility" to Icons.Filled.SettingsAccessibility,
    "Settings Applications" to Icons.Filled.SettingsApplications,
    "Settings Backup Restore" to Icons.Filled.SettingsBackupRestore,
    "Settings Bluetooth" to Icons.Filled.SettingsBluetooth,
    "Settings Brightness" to Icons.Filled.SettingsBrightness,
    "Settings Ethernet" to Icons.Filled.SettingsEthernet,
    "Settings Input Antenna" to Icons.Filled.SettingsInputAntenna,
    "Settings Input Component" to Icons.Filled.SettingsInputComponent,
    "Settings Input Hdmi" to Icons.Filled.SettingsInputHdmi,
    "Settings Input Svideo" to Icons.Filled.SettingsInputSvideo,
    "Settings Overscan" to Icons.Filled.SettingsOverscan,
    "Settings Phone" to Icons.Filled.SettingsPhone,
    "Settings Power" to Icons.Filled.SettingsPower,
    "Settings Remote" to Icons.Filled.SettingsRemote,
    "Settings Suggest" to Icons.Filled.SettingsSuggest,
    "Settings System Daydream" to Icons.Filled.SettingsSystemDaydream,
    "Settings Voice" to Icons.Filled.SettingsVoice,
    "Severe Cold" to Icons.Filled.SevereCold,
    "Shape Line" to Icons.Filled.ShapeLine,
    "Share Location" to Icons.Filled.ShareLocation,
    "Shield" to Icons.Filled.Shield,
    "Shield Moon" to Icons.Filled.ShieldMoon,
    "Shop" to Icons.Filled.Shop,
    "Shop Two" to Icons.Filled.ShopTwo,
    "Shopping Bag" to Icons.Filled.ShoppingBag,
    "Shopping Basket" to Icons.Filled.ShoppingBasket,
    "Shopping Cart Checkout" to Icons.Filled.ShoppingCartCheckout,
    "Short Text" to Icons.Filled.ShortText,
    "Show Chart" to Icons.Filled.ShowChart,
    "Shower" to Icons.Filled.Shower,
    "Shuffle" to Icons.Filled.Shuffle,
    "Shuffle On" to Icons.Filled.ShuffleOn,
    "Shutter Speed" to Icons.Filled.ShutterSpeed,
    "Sick" to Icons.Filled.Sick,
    "Sign Language" to Icons.Filled.SignLanguage,
    "Signal Cellular0 Bar" to Icons.Filled.SignalCellular0Bar,
    "Signal Cellular4 Bar" to Icons.Filled.SignalCellular4Bar,
    "Signal Cellular Alt" to Icons.Filled.SignalCellularAlt,
    "Signal Cellular Alt1 Bar" to Icons.Filled.SignalCellularAlt1Bar,
    "Signal Cellular Alt2 Bar" to Icons.Filled.SignalCellularAlt2Bar,
    "Signal Cellular Connected No Internet0 Bar" to Icons.Filled.SignalCellularConnectedNoInternet0Bar,
    "Signal Cellular Connected No Internet4 Bar" to Icons.Filled.SignalCellularConnectedNoInternet4Bar,
    "Signal Cellular Nodata" to Icons.Filled.SignalCellularNodata,
    "Signal Cellular Null" to Icons.Filled.SignalCellularNull,
    "Signal Cellular Off" to Icons.Filled.SignalCellularOff,
    "Signal Wifi0 Bar" to Icons.Filled.SignalWifi0Bar,
    "Signal Wifi4 Bar" to Icons.Filled.SignalWifi4Bar,
    "Signal Wifi Bad" to Icons.Filled.SignalWifiBad,
    "Signal Wifi Off" to Icons.Filled.SignalWifiOff,
    "Signal Wifi Statusbar Null" to Icons.Filled.SignalWifiStatusbarNull,
    "Signpost" to Icons.Filled.Signpost,
    "Sim Card" to Icons.Filled.SimCard,
    "Sim Card Download" to Icons.Filled.SimCardDownload,
    "Single Bed" to Icons.Filled.SingleBed,
    "Sip" to Icons.Filled.Sip,
    "Skateboarding" to Icons.Filled.Skateboarding,
    "Skip Next" to Icons.Filled.SkipNext,
    "Skip Previous" to Icons.Filled.SkipPrevious,
    "Sledding" to Icons.Filled.Sledding,
    "Slideshow" to Icons.Filled.Slideshow,
    "Slow Motion Video" to Icons.Filled.SlowMotionVideo,
    "Smart Button" to Icons.Filled.SmartButton,
    "Smart Display" to Icons.Filled.SmartDisplay,
    "Smart Toy" to Icons.Filled.SmartToy,
    "Smoke Free" to Icons.Filled.SmokeFree,
    "Smoking Rooms" to Icons.Filled.SmokingRooms,
    "Sms" to Icons.Filled.Sms,
    "Sms Failed" to Icons.Filled.SmsFailed,
    "Snippet Folder" to Icons.Filled.SnippetFolder,
    "Snooze" to Icons.Filled.Snooze,
    "Snowboarding" to Icons.Filled.Snowboarding,
    "Snowmobile" to Icons.Filled.Snowmobile,
    "Snowshoeing" to Icons.Filled.Snowshoeing,
    "Soap" to Icons.Filled.Soap,
    "Social Distance" to Icons.Filled.SocialDistance,
    "Solar Power" to Icons.Filled.SolarPower,
    "Sort" to Icons.Filled.Sort,
    "Sort By Alpha" to Icons.Filled.SortByAlpha,
    "Sos" to Icons.Filled.Sos,
    "Soup Kitchen" to Icons.Filled.SoupKitchen,
    "South" to Icons.Filled.South,
    "South America" to Icons.Filled.SouthAmerica,
    "South East" to Icons.Filled.SouthEast,
    "South West" to Icons.Filled.SouthWest,
    "Spa" to Icons.Filled.Spa,
    "Space Bar" to Icons.Filled.SpaceBar,
    "Space Dashboard" to Icons.Filled.SpaceDashboard,
    "Spatial Audio" to Icons.Filled.SpatialAudio,
    "Spatial Audio Off" to Icons.Filled.SpatialAudioOff,
    "Spatial Tracking" to Icons.Filled.SpatialTracking,
    "Speaker" to Icons.Filled.Speaker,
    "Speaker Group" to Icons.Filled.SpeakerGroup,
    "Speaker Notes" to Icons.Filled.SpeakerNotes,
    "Speaker Notes Off" to Icons.Filled.SpeakerNotesOff,
    "Speaker Phone" to Icons.Filled.SpeakerPhone,
    "Speed" to Icons.Filled.Speed,
    "Spellcheck" to Icons.Filled.Spellcheck,
    "Splitscreen" to Icons.Filled.Splitscreen,
    "Spoke" to Icons.Filled.Spoke,
    "Sports" to Icons.Filled.Sports,
    "Sports Bar" to Icons.Filled.SportsBar,
    "Sports Baseball" to Icons.Filled.SportsBaseball,
    "Sports Basketball" to Icons.Filled.SportsBasketball,
    "Sports Cricket" to Icons.Filled.SportsCricket,
    "Sports Esports" to Icons.Filled.SportsEsports,
    "Sports Football" to Icons.Filled.SportsFootball,
    "Sports Golf" to Icons.Filled.SportsGolf,
    "Sports Gymnastics" to Icons.Filled.SportsGymnastics,
    "Sports Handball" to Icons.Filled.SportsHandball,
    "Sports Hockey" to Icons.Filled.SportsHockey,
    "Sports Kabaddi" to Icons.Filled.SportsKabaddi,
    "Sports Martial Arts" to Icons.Filled.SportsMartialArts,
    "Sports Mma" to Icons.Filled.SportsMma,
    "Sports Motorsports" to Icons.Filled.SportsMotorsports,
    "Sports Rugby" to Icons.Filled.SportsRugby,
    "Sports Score" to Icons.Filled.SportsScore,
    "Sports Soccer" to Icons.Filled.SportsSoccer,
    "Sports Tennis" to Icons.Filled.SportsTennis,
    "Sports Volleyball" to Icons.Filled.SportsVolleyball,
    "Square" to Icons.Filled.Square,
    "Square Foot" to Icons.Filled.SquareFoot,
    "Ssid Chart" to Icons.Filled.SsidChart,
    "Stacked Bar Chart" to Icons.Filled.StackedBarChart,
    "Stacked Line Chart" to Icons.Filled.StackedLineChart,
    "Stadium" to Icons.Filled.Stadium,
    "Stairs" to Icons.Filled.Stairs,
    "Star Half" to Icons.Filled.StarHalf,
    "Star Rate" to Icons.Filled.StarRate,
    "Stars" to Icons.Filled.Stars,
    "Start" to Icons.Filled.Start,
    "Sticky Note2" to Icons.Filled.StickyNote2,
    "Stop" to Icons.Filled.Stop,
    "Stop Circle" to Icons.Filled.StopCircle,
    "Stop Screen Share" to Icons.Filled.StopScreenShare,
    "Storage" to Icons.Filled.Storage,
    "Store" to Icons.Filled.Store,
    "Storefront" to Icons.Filled.Storefront,
    "Storm" to Icons.Filled.Storm,
    "Straight" to Icons.Filled.Straight,
    "Straighten" to Icons.Filled.Straighten,
    "Stream" to Icons.Filled.Stream,
    "Streetview" to Icons.Filled.Streetview,
    "Strikethrough S" to Icons.Filled.StrikethroughS,
    "Stroller" to Icons.Filled.Stroller,
    "Style" to Icons.Filled.Style,
    "Subdirectory Arrow Left" to Icons.Filled.SubdirectoryArrowLeft,
    "Subdirectory Arrow Right" to Icons.Filled.SubdirectoryArrowRight,
    "Subject" to Icons.Filled.Subject,
    "Subscript" to Icons.Filled.Subscript,
    "Subscriptions" to Icons.Filled.Subscriptions,
    "Subtitles" to Icons.Filled.Subtitles,
    "Subtitles Off" to Icons.Filled.SubtitlesOff,
    "Subway" to Icons.Filled.Subway,
    "Summarize" to Icons.Filled.Summarize,
    "Superscript" to Icons.Filled.Superscript,
    "Supervised User Circle" to Icons.Filled.SupervisedUserCircle,
    "Supervisor Account" to Icons.Filled.SupervisorAccount,
    "Support" to Icons.Filled.Support,
    "Support Agent" to Icons.Filled.SupportAgent,
    "Surfing" to Icons.Filled.Surfing,
    "Surround Sound" to Icons.Filled.SurroundSound,
    "Swap Calls" to Icons.Filled.SwapCalls,
    "Swap Horiz" to Icons.Filled.SwapHoriz,
    "Swap Horizontal Circle" to Icons.Filled.SwapHorizontalCircle,
    "Swap Vert" to Icons.Filled.SwapVert,
    "Swap Vertical Circle" to Icons.Filled.SwapVerticalCircle,
    "Swipe" to Icons.Filled.Swipe,
    "Swipe Down" to Icons.Filled.SwipeDown,
    "Swipe Down Alt" to Icons.Filled.SwipeDownAlt,
    "Swipe Left" to Icons.Filled.SwipeLeft,
    "Swipe Left Alt" to Icons.Filled.SwipeLeftAlt,
    "Swipe Right" to Icons.Filled.SwipeRight,
    "Swipe Right Alt" to Icons.Filled.SwipeRightAlt,
    "Swipe Up" to Icons.Filled.SwipeUp,
    "Swipe Up Alt" to Icons.Filled.SwipeUpAlt,
    "Swipe Vertical" to Icons.Filled.SwipeVertical,
    "Switch Access Shortcut" to Icons.Filled.SwitchAccessShortcut,
    "Switch Access Shortcut Add" to Icons.Filled.SwitchAccessShortcutAdd,
    "Switch Account" to Icons.Filled.SwitchAccount,
    "Switch Camera" to Icons.Filled.SwitchCamera,
    "Switch Left" to Icons.Filled.SwitchLeft,
    "Switch Right" to Icons.Filled.SwitchRight,
    "Switch Video" to Icons.Filled.SwitchVideo,
    "Synagogue" to Icons.Filled.Synagogue,
    "Sync" to Icons.Filled.Sync,
    "Sync Alt" to Icons.Filled.SyncAlt,
    "Sync Disabled" to Icons.Filled.SyncDisabled,
    "Sync Lock" to Icons.Filled.SyncLock,
    "Sync Problem" to Icons.Filled.SyncProblem,
    "System Update Alt" to Icons.Filled.SystemUpdateAlt,
    "Tab" to Icons.Filled.Tab,
    "Tab Unselected" to Icons.Filled.TabUnselected,
    "Table Bar" to Icons.Filled.TableBar,
    "Table Chart" to Icons.Filled.TableChart,
    "Table Restaurant" to Icons.Filled.TableRestaurant,
    "Table Rows" to Icons.Filled.TableRows,
    "Table View" to Icons.Filled.TableView,
    "Tablet" to Icons.Filled.Tablet,
    "Tablet Android" to Icons.Filled.TabletAndroid,
    "Tablet Mac" to Icons.Filled.TabletMac,
    "Tag" to Icons.Filled.Tag,
    "Takeout Dining" to Icons.Filled.TakeoutDining,
    "Tapas" to Icons.Filled.Tapas,
    "Task" to Icons.Filled.Task,
    "Task Alt" to Icons.Filled.TaskAlt,
    "Taxi Alert" to Icons.Filled.TaxiAlert,
    "Temple Buddhist" to Icons.Filled.TempleBuddhist,
    "Temple Hindu" to Icons.Filled.TempleHindu,
    "Terminal" to Icons.Filled.Terminal,
    "Text Decrease" to Icons.Filled.TextDecrease,
    "Text Fields" to Icons.Filled.TextFields,
    "Text Format" to Icons.Filled.TextFormat,
    "Text Increase" to Icons.Filled.TextIncrease,
    "Text Rotate Up" to Icons.Filled.TextRotateUp,
    "Text Rotate Vertical" to Icons.Filled.TextRotateVertical,
    "Text Rotation Angledown" to Icons.Filled.TextRotationAngledown,
    "Text Rotation Angleup" to Icons.Filled.TextRotationAngleup,
    "Text Rotation Down" to Icons.Filled.TextRotationDown,
    "Text Rotation None" to Icons.Filled.TextRotationNone,
    "Text Snippet" to Icons.Filled.TextSnippet,
    "Texture" to Icons.Filled.Texture,
    "Theater Comedy" to Icons.Filled.TheaterComedy,
    "Theaters" to Icons.Filled.Theaters,
    "Thermostat" to Icons.Filled.Thermostat,
    "Thermostat Auto" to Icons.Filled.ThermostatAuto,
    "Thumb Down" to Icons.Filled.ThumbDown,
    "Thumbs Up Down" to Icons.Filled.ThumbsUpDown,
    "Thunderstorm" to Icons.Filled.Thunderstorm,
    "Timelapse" to Icons.Filled.Timelapse,
    "Timeline" to Icons.Filled.Timeline,
    "Timer" to Icons.Filled.Timer,
    "Timer10" to Icons.Filled.Timer10,
    "Timer10 Select" to Icons.Filled.Timer10Select,
    "Timer3" to Icons.Filled.Timer3,
    "Timer3 Select" to Icons.Filled.Timer3Select,
    "Timer Off" to Icons.Filled.TimerOff,
    "Tips And Updates" to Icons.Filled.TipsAndUpdates,
    "Tire Repair" to Icons.Filled.TireRepair,
    "Title" to Icons.Filled.Title,
    "Toc" to Icons.Filled.Toc,
    "Today" to Icons.Filled.Today,
    "Toggle Off" to Icons.Filled.ToggleOff,
    "Toggle On" to Icons.Filled.ToggleOn,
    "Token" to Icons.Filled.Token,
    "Toll" to Icons.Filled.Toll,
    "Tonality" to Icons.Filled.Tonality,
    "Topic" to Icons.Filled.Topic,
    "Tornado" to Icons.Filled.Tornado,
    "Touch App" to Icons.Filled.TouchApp,
    "Tour" to Icons.Filled.Tour,
    "Toys" to Icons.Filled.Toys,
    "Track Changes" to Icons.Filled.TrackChanges,
    "Traffic" to Icons.Filled.Traffic,
    "Train" to Icons.Filled.Train,
    "Tram" to Icons.Filled.Tram,
    "Transcribe" to Icons.Filled.Transcribe,
    "Transfer Within A Station" to Icons.Filled.TransferWithinAStation,
    "Transform" to Icons.Filled.Transform,
    "Transgender" to Icons.Filled.Transgender,
    "Transit Enterexit" to Icons.Filled.TransitEnterexit,
    "Translate" to Icons.Filled.Translate,
    "Travel Explore" to Icons.Filled.TravelExplore,
    "Trending Down" to Icons.Filled.TrendingDown,
    "Trending Flat" to Icons.Filled.TrendingFlat,
    "Trending Up" to Icons.Filled.TrendingUp,
    "Trip Origin" to Icons.Filled.TripOrigin,
    "Troubleshoot" to Icons.Filled.Troubleshoot,
    "Tsunami" to Icons.Filled.Tsunami,
    "Tty" to Icons.Filled.Tty,
    "Tune" to Icons.Filled.Tune,
    "Turn Left" to Icons.Filled.TurnLeft,
    "Turn Right" to Icons.Filled.TurnRight,
    "Turn Sharp Left" to Icons.Filled.TurnSharpLeft,
    "Turn Sharp Right" to Icons.Filled.TurnSharpRight,
    "Turn Slight Left" to Icons.Filled.TurnSlightLeft,
    "Turn Slight Right" to Icons.Filled.TurnSlightRight,
    "Tv" to Icons.Filled.Tv,
    "Tv Off" to Icons.Filled.TvOff,
    "Two Wheeler" to Icons.Filled.TwoWheeler,
    "Type Specimen" to Icons.Filled.TypeSpecimen,
    "U Turn Left" to Icons.Filled.UTurnLeft,
    "U Turn Right" to Icons.Filled.UTurnRight,
    "Umbrella" to Icons.Filled.Umbrella,
    "Unarchive" to Icons.Filled.Unarchive,
    "Undo" to Icons.Filled.Undo,
    "Unfold Less" to Icons.Filled.UnfoldLess,
    "Unfold Less Double" to Icons.Filled.UnfoldLessDouble,
    "Unfold More" to Icons.Filled.UnfoldMore,
    "Unfold More Double" to Icons.Filled.UnfoldMoreDouble,
    "Unpublished" to Icons.Filled.Unpublished,
    "Unsubscribe" to Icons.Filled.Unsubscribe,
    "Upcoming" to Icons.Filled.Upcoming,
    "Update" to Icons.Filled.Update,
    "Update Disabled" to Icons.Filled.UpdateDisabled,
    "Upgrade" to Icons.Filled.Upgrade,
    "Upload" to Icons.Filled.Upload,
    "Upload File" to Icons.Filled.UploadFile,
    "Usb" to Icons.Filled.Usb,
    "Usb Off" to Icons.Filled.UsbOff,
    "Vaccines" to Icons.Filled.Vaccines,
    "Vape Free" to Icons.Filled.VapeFree,
    "Vaping Rooms" to Icons.Filled.VapingRooms,
    "Verified" to Icons.Filled.Verified,
    "Verified User" to Icons.Filled.VerifiedUser,
    "Vertical Align Bottom" to Icons.Filled.VerticalAlignBottom,
    "Vertical Align Center" to Icons.Filled.VerticalAlignCenter,
    "Vertical Align Top" to Icons.Filled.VerticalAlignTop,
    "Vertical Distribute" to Icons.Filled.VerticalDistribute,
    "Vertical Shades" to Icons.Filled.VerticalShades,
    "Vertical Shades Closed" to Icons.Filled.VerticalShadesClosed,
    "Vertical Split" to Icons.Filled.VerticalSplit,
    "Video Call" to Icons.Filled.VideoCall,
    "Video Camera Back" to Icons.Filled.VideoCameraBack,
    "Video Camera Front" to Icons.Filled.VideoCameraFront,
    "Video Chat" to Icons.Filled.VideoChat,
    "Video File" to Icons.Filled.VideoFile,
    "Video Label" to Icons.Filled.VideoLabel,
    "Video Library" to Icons.Filled.VideoLibrary,
    "Video Settings" to Icons.Filled.VideoSettings,
    "Video Stable" to Icons.Filled.VideoStable,
    "Videocam" to Icons.Filled.Videocam,
    "Videocam Off" to Icons.Filled.VideocamOff,
    "Videogame Asset" to Icons.Filled.VideogameAsset,
    "Videogame Asset Off" to Icons.Filled.VideogameAssetOff,
    "View Agenda" to Icons.Filled.ViewAgenda,
    "View Array" to Icons.Filled.ViewArray,
    "View Carousel" to Icons.Filled.ViewCarousel,
    "View Column" to Icons.Filled.ViewColumn,
    "View Comfy" to Icons.Filled.ViewComfy,
    "View Comfy Alt" to Icons.Filled.ViewComfyAlt,
    "View Compact" to Icons.Filled.ViewCompact,
    "View Compact Alt" to Icons.Filled.ViewCompactAlt,
    "View Cozy" to Icons.Filled.ViewCozy,
    "View Day" to Icons.Filled.ViewDay,
    "View Headline" to Icons.Filled.ViewHeadline,
    "View In Ar" to Icons.Filled.ViewInAr,
    "View Kanban" to Icons.Filled.ViewKanban,
    "View List" to Icons.Filled.ViewList,
    "View Module" to Icons.Filled.ViewModule,
    "View Quilt" to Icons.Filled.ViewQuilt,
    "View Sidebar" to Icons.Filled.ViewSidebar,
    "View Stream" to Icons.Filled.ViewStream,
    "View Timeline" to Icons.Filled.ViewTimeline,
    "View Week" to Icons.Filled.ViewWeek,
    "Vignette" to Icons.Filled.Vignette,
    "Villa" to Icons.Filled.Villa,
    "Visibility" to Icons.Filled.Visibility,
    "Visibility Off" to Icons.Filled.VisibilityOff,
    "Voice Chat" to Icons.Filled.VoiceChat,
    "Voice Over Off" to Icons.Filled.VoiceOverOff,
    "Voicemail" to Icons.Filled.Voicemail,
    "Volcano" to Icons.Filled.Volcano,
    "Volume Down" to Icons.Filled.VolumeDown,
    "Volume Mute" to Icons.Filled.VolumeMute,
    "Volume Off" to Icons.Filled.VolumeOff,
    "Volume Up" to Icons.Filled.VolumeUp,
    "Volunteer Activism" to Icons.Filled.VolunteerActivism,
    "Vpn Key" to Icons.Filled.VpnKey,
    "Vpn Key Off" to Icons.Filled.VpnKeyOff,
    "Vpn Lock" to Icons.Filled.VpnLock,
    "Vrpano" to Icons.Filled.Vrpano,
    "Wallet" to Icons.Filled.Wallet,
    "Wallpaper" to Icons.Filled.Wallpaper,
    "Warehouse" to Icons.Filled.Warehouse,
    "Wash" to Icons.Filled.Wash,
    "Watch" to Icons.Filled.Watch,
    "Watch Off" to Icons.Filled.WatchOff,
    "Water" to Icons.Filled.Water,
    "Water Damage" to Icons.Filled.WaterDamage,
    "Water Drop" to Icons.Filled.WaterDrop,
    "Waterfall Chart" to Icons.Filled.WaterfallChart,
    "Waves" to Icons.Filled.Waves,
    "Waving Hand" to Icons.Filled.WavingHand,
    "Wb Auto" to Icons.Filled.WbAuto,
    "Wb Incandescent" to Icons.Filled.WbIncandescent,
    "Wb Iridescent" to Icons.Filled.WbIridescent,
    "Wb Shade" to Icons.Filled.WbShade,
    "Wb Sunny" to Icons.Filled.WbSunny,
    "Wb Twilight" to Icons.Filled.WbTwilight,
    "Wc" to Icons.Filled.Wc,
    "Web" to Icons.Filled.Web,
    "Web Asset" to Icons.Filled.WebAsset,
    "Web Asset Off" to Icons.Filled.WebAssetOff,
    "Web Stories" to Icons.Filled.WebStories,
    "Webhook" to Icons.Filled.Webhook,
    "Weekend" to Icons.Filled.Weekend,
    "West" to Icons.Filled.West,
    "Whatshot" to Icons.Filled.Whatshot,
    "Wheelchair Pickup" to Icons.Filled.WheelchairPickup,
    "Where To Vote" to Icons.Filled.WhereToVote,
    "Widgets" to Icons.Filled.Widgets,
    "Width Full" to Icons.Filled.WidthFull,
    "Width Normal" to Icons.Filled.WidthNormal,
    "Width Wide" to Icons.Filled.WidthWide,
    "Wifi" to Icons.Filled.Wifi,
    "Wifi1 Bar" to Icons.Filled.Wifi1Bar,
    "Wifi2 Bar" to Icons.Filled.Wifi2Bar,
    "Wifi Calling" to Icons.Filled.WifiCalling,
    "Wifi Channel" to Icons.Filled.WifiChannel,
    "Wifi Find" to Icons.Filled.WifiFind,
    "Wifi Lock" to Icons.Filled.WifiLock,
    "Wifi Off" to Icons.Filled.WifiOff,
    "Wifi Password" to Icons.Filled.WifiPassword,
    "Wifi Protected Setup" to Icons.Filled.WifiProtectedSetup,
    "Wifi Tethering" to Icons.Filled.WifiTethering,
    "Wifi Tethering Error" to Icons.Filled.WifiTetheringError,
    "Wifi Tethering Off" to Icons.Filled.WifiTetheringOff,
    "Wind Power" to Icons.Filled.WindPower,
    "Window" to Icons.Filled.Window,
    "Wine Bar" to Icons.Filled.WineBar,
    "Woman" to Icons.Filled.Woman,
    "Woman2" to Icons.Filled.Woman2,
    "Work" to Icons.Filled.Work,
    "Work History" to Icons.Filled.WorkHistory,
    "Work Off" to Icons.Filled.WorkOff,
    "Workspace Premium" to Icons.Filled.WorkspacePremium,
    "Workspaces" to Icons.Filled.Workspaces,
    "Wrap Text" to Icons.Filled.WrapText,
    "Wrong Location" to Icons.Filled.WrongLocation,
    "Wysiwyg" to Icons.Filled.Wysiwyg,
    "Yard" to Icons.Filled.Yard,
    "Youtube Searched For" to Icons.Filled.YoutubeSearchedFor,
    "Zoom In" to Icons.Filled.ZoomIn,
    "Zoom In Map" to Icons.Filled.ZoomInMap,
    "Zoom Out" to Icons.Filled.ZoomOut,
    "Zoom Out Map" to Icons.Filled.ZoomOutMap,
    "10k" to Icons.Filled._10k,
    "10mp" to Icons.Filled._10mp,
    "11mp" to Icons.Filled._11mp,
    "123" to Icons.Filled._123,
    "12mp" to Icons.Filled._12mp,
    "13mp" to Icons.Filled._13mp,
    "14mp" to Icons.Filled._14mp,
    "15mp" to Icons.Filled._15mp,
    "16mp" to Icons.Filled._16mp,
    "17mp" to Icons.Filled._17mp,
    "18 Up Rating" to Icons.Filled._18UpRating,
    "18mp" to Icons.Filled._18mp,
    "19mp" to Icons.Filled._19mp,
    "1k" to Icons.Filled._1k,
    "1k Plus" to Icons.Filled._1kPlus,
    "1x Mobiledata" to Icons.Filled._1xMobiledata,
    "20mp" to Icons.Filled._20mp,
    "21mp" to Icons.Filled._21mp,
    "22mp" to Icons.Filled._22mp,
    "23mp" to Icons.Filled._23mp,
    "24mp" to Icons.Filled._24mp,
    "2k" to Icons.Filled._2k,
    "2k Plus" to Icons.Filled._2kPlus,
    "2mp" to Icons.Filled._2mp,
    "30fps" to Icons.Filled._30fps,
    "30fps Select" to Icons.Filled._30fpsSelect,
    "360" to Icons.Filled._360,
    "3d Rotation" to Icons.Filled._3dRotation,
    "3g Mobiledata" to Icons.Filled._3gMobiledata,
    "3k" to Icons.Filled._3k,
    "3k Plus" to Icons.Filled._3kPlus,
    "3mp" to Icons.Filled._3mp,
    "3p" to Icons.Filled._3p,
    "4g Mobiledata" to Icons.Filled._4gMobiledata,
    "4g Plus Mobiledata" to Icons.Filled._4gPlusMobiledata,
    "4k" to Icons.Filled._4k,
    "4k Plus" to Icons.Filled._4kPlus,
    "4mp" to Icons.Filled._4mp,
    "5g" to Icons.Filled._5g,
    "5k" to Icons.Filled._5k,
    "5k Plus" to Icons.Filled._5kPlus,
    "5mp" to Icons.Filled._5mp,
    "60fps" to Icons.Filled._60fps,
    "60fps Select" to Icons.Filled._60fpsSelect,
    "6 Ft Apart" to Icons.Filled._6FtApart,
    "6k" to Icons.Filled._6k,
    "6k Plus" to Icons.Filled._6kPlus,
    "6mp" to Icons.Filled._6mp,
    "7k" to Icons.Filled._7k,
    "7k Plus" to Icons.Filled._7kPlus,
    "7mp" to Icons.Filled._7mp,
    "8k" to Icons.Filled._8k,
    "8k Plus" to Icons.Filled._8kPlus,
    "8mp" to Icons.Filled._8mp,
    "9k" to Icons.Filled._9k,
    "9k Plus" to Icons.Filled._9kPlus,
    "9mp" to Icons.Filled._9mp,
)

val extendedOnlyAutoMirroredFilledIconNamePairs: List<Pair<String, Icon>> = listOf(
    "Accessible" to Icons.AutoMirrored.Filled.Accessible,
    "Accessible Forward" to Icons.AutoMirrored.Filled.AccessibleForward,
    "Airplane Ticket" to Icons.AutoMirrored.Filled.AirplaneTicket,
    "Align Horizontal Left" to Icons.AutoMirrored.Filled.AlignHorizontalLeft,
    "Align Horizontal Right" to Icons.AutoMirrored.Filled.AlignHorizontalRight,
    "Alt Route" to Icons.AutoMirrored.Filled.AltRoute,
    "Arrow Back Ios" to Icons.AutoMirrored.Filled.ArrowBackIos,
    "Arrow Forward Ios" to Icons.AutoMirrored.Filled.ArrowForwardIos,
    "Arrow Left" to Icons.AutoMirrored.Filled.ArrowLeft,
    "Arrow Right" to Icons.AutoMirrored.Filled.ArrowRight,
    "Arrow Right Alt" to Icons.AutoMirrored.Filled.ArrowRightAlt,
    "Article" to Icons.AutoMirrored.Filled.Article,
    "Assignment" to Icons.AutoMirrored.Filled.Assignment,
    "Assignment Return" to Icons.AutoMirrored.Filled.AssignmentReturn,
    "Assistant Direction" to Icons.AutoMirrored.Filled.AssistantDirection,
    "Backspace" to Icons.AutoMirrored.Filled.Backspace,
    "Battery Unknown" to Icons.AutoMirrored.Filled.BatteryUnknown,
    "Bluetooth Searching" to Icons.AutoMirrored.Filled.BluetoothSearching,
    "Branding Watermark" to Icons.AutoMirrored.Filled.BrandingWatermark,
    "Call Made" to Icons.AutoMirrored.Filled.CallMade,
    "Call Merge" to Icons.AutoMirrored.Filled.CallMerge,
    "Call Missed" to Icons.AutoMirrored.Filled.CallMissed,
    "Call Missed Outgoing" to Icons.AutoMirrored.Filled.CallMissedOutgoing,
    "Call Received" to Icons.AutoMirrored.Filled.CallReceived,
    "Call Split" to Icons.AutoMirrored.Filled.CallSplit,
    "Chat" to Icons.AutoMirrored.Filled.Chat,
    "Chrome Reader Mode" to Icons.AutoMirrored.Filled.ChromeReaderMode,
    "Comment" to Icons.AutoMirrored.Filled.Comment,
    "Compare Arrows" to Icons.AutoMirrored.Filled.CompareArrows,
    "Contact Support" to Icons.AutoMirrored.Filled.ContactSupport,
    "Directions Bike" to Icons.AutoMirrored.Filled.DirectionsBike,
    "Directions Run" to Icons.AutoMirrored.Filled.DirectionsRun,
    "Directions Walk" to Icons.AutoMirrored.Filled.DirectionsWalk,
    "Drive File Move" to Icons.AutoMirrored.Filled.DriveFileMove,
    "Dvr" to Icons.AutoMirrored.Filled.Dvr,
    "Event Note" to Icons.AutoMirrored.Filled.EventNote,
    "Fact Check" to Icons.AutoMirrored.Filled.FactCheck,
    "Featured Play List" to Icons.AutoMirrored.Filled.FeaturedPlayList,
    "Featured Video" to Icons.AutoMirrored.Filled.FeaturedVideo,
    "Feed" to Icons.AutoMirrored.Filled.Feed,
    "Follow The Signs" to Icons.AutoMirrored.Filled.FollowTheSigns,
    "Format Align Left" to Icons.AutoMirrored.Filled.FormatAlignLeft,
    "Format Align Right" to Icons.AutoMirrored.Filled.FormatAlignRight,
    "Format Indent Decrease" to Icons.AutoMirrored.Filled.FormatIndentDecrease,
    "Format Indent Increase" to Icons.AutoMirrored.Filled.FormatIndentIncrease,
    "Format List Bulleted" to Icons.AutoMirrored.Filled.FormatListBulleted,
    "Format Textdirection L To R" to Icons.AutoMirrored.Filled.FormatTextdirectionLToR,
    "Format Textdirection R To L" to Icons.AutoMirrored.Filled.FormatTextdirectionRToL,
    "Forward" to Icons.AutoMirrored.Filled.Forward,
    "Forward To Inbox" to Icons.AutoMirrored.Filled.ForwardToInbox,
    "Grading" to Icons.AutoMirrored.Filled.Grading,
    "Help" to Icons.AutoMirrored.Filled.Help,
    "Help Center" to Icons.AutoMirrored.Filled.HelpCenter,
    "Input" to Icons.AutoMirrored.Filled.Input,
    "Keyboard Backspace" to Icons.AutoMirrored.Filled.KeyboardBackspace,
    "Keyboard Return" to Icons.AutoMirrored.Filled.KeyboardReturn,
    "Keyboard Tab" to Icons.AutoMirrored.Filled.KeyboardTab,
    "Label" to Icons.AutoMirrored.Filled.Label,
    "Label Important" to Icons.AutoMirrored.Filled.LabelImportant,
    "Label Off" to Icons.AutoMirrored.Filled.LabelOff,
    "Last Page" to Icons.AutoMirrored.Filled.LastPage,
    "Library Books" to Icons.AutoMirrored.Filled.LibraryBooks,
    "List Alt" to Icons.AutoMirrored.Filled.ListAlt,
    "Live Help" to Icons.AutoMirrored.Filled.LiveHelp,
    "Login" to Icons.AutoMirrored.Filled.Login,
    "Logout" to Icons.AutoMirrored.Filled.Logout,
    "Manage Search" to Icons.AutoMirrored.Filled.ManageSearch,
    "Menu Book" to Icons.AutoMirrored.Filled.MenuBook,
    "Menu Open" to Icons.AutoMirrored.Filled.MenuOpen,
    "Merge Type" to Icons.AutoMirrored.Filled.MergeType,
    "Missed Video Call" to Icons.AutoMirrored.Filled.MissedVideoCall,
    "More" to Icons.AutoMirrored.Filled.More,
    "Multiline Chart" to Icons.AutoMirrored.Filled.MultilineChart,
    "Next Plan" to Icons.AutoMirrored.Filled.NextPlan,
    "Next Week" to Icons.AutoMirrored.Filled.NextWeek,
    "Not Listed Location" to Icons.AutoMirrored.Filled.NotListedLocation,
    "Note" to Icons.AutoMirrored.Filled.Note,
    "Note Add" to Icons.AutoMirrored.Filled.NoteAdd,
    "Notes" to Icons.AutoMirrored.Filled.Notes,
    "Open In New" to Icons.AutoMirrored.Filled.OpenInNew,
    "Outbound" to Icons.AutoMirrored.Filled.Outbound,
    "Phone Callback" to Icons.AutoMirrored.Filled.PhoneCallback,
    "Phone Forwarded" to Icons.AutoMirrored.Filled.PhoneForwarded,
    "Phone Missed" to Icons.AutoMirrored.Filled.PhoneMissed,
    "Playlist Add" to Icons.AutoMirrored.Filled.PlaylistAdd,
    "Playlist Add Check" to Icons.AutoMirrored.Filled.PlaylistAddCheck,
    "Playlist Play" to Icons.AutoMirrored.Filled.PlaylistPlay,
    "Queue Music" to Icons.AutoMirrored.Filled.QueueMusic,
    "Read More" to Icons.AutoMirrored.Filled.ReadMore,
    "Receipt Long" to Icons.AutoMirrored.Filled.ReceiptLong,
    "Redo" to Icons.AutoMirrored.Filled.Redo,
    "Reply" to Icons.AutoMirrored.Filled.Reply,
    "Reply All" to Icons.AutoMirrored.Filled.ReplyAll,
    "Rotate Left" to Icons.AutoMirrored.Filled.RotateLeft,
    "Rotate Right" to Icons.AutoMirrored.Filled.RotateRight,
    "Rtt" to Icons.AutoMirrored.Filled.Rtt,
    "Rule" to Icons.AutoMirrored.Filled.Rule,
    "Schedule Send" to Icons.AutoMirrored.Filled.ScheduleSend,
    "Screen Share" to Icons.AutoMirrored.Filled.ScreenShare,
    "Segment" to Icons.AutoMirrored.Filled.Segment,
    "Send And Archive" to Icons.AutoMirrored.Filled.SendAndArchive,
    "Short Text" to Icons.AutoMirrored.Filled.ShortText,
    "Show Chart" to Icons.AutoMirrored.Filled.ShowChart,
    "Sort" to Icons.AutoMirrored.Filled.Sort,
    "Speaker Notes" to Icons.AutoMirrored.Filled.SpeakerNotes,
    "Star Half" to Icons.AutoMirrored.Filled.StarHalf,
    "Sticky Note2" to Icons.AutoMirrored.Filled.StickyNote2,
    "Stop Screen Share" to Icons.AutoMirrored.Filled.StopScreenShare,
    "Subject" to Icons.AutoMirrored.Filled.Subject,
    "Text Snippet" to Icons.AutoMirrored.Filled.TextSnippet,
    "Toc" to Icons.AutoMirrored.Filled.Toc,
    "Trending Down" to Icons.AutoMirrored.Filled.TrendingDown,
    "Trending Flat" to Icons.AutoMirrored.Filled.TrendingFlat,
    "Trending Up" to Icons.AutoMirrored.Filled.TrendingUp,
    "Undo" to Icons.AutoMirrored.Filled.Undo,
    "View List" to Icons.AutoMirrored.Filled.ViewList,
    "View Quilt" to Icons.AutoMirrored.Filled.ViewQuilt,
    "View Sidebar" to Icons.AutoMirrored.Filled.ViewSidebar,
    "Volume Down" to Icons.AutoMirrored.Filled.VolumeDown,
    "Volume Mute" to Icons.AutoMirrored.Filled.VolumeMute,
    "Volume Off" to Icons.AutoMirrored.Filled.VolumeOff,
    "Volume Up" to Icons.AutoMirrored.Filled.VolumeUp,
    "Wrap Text" to Icons.AutoMirrored.Filled.WrapText,
    "Wysiwyg" to Icons.AutoMirrored.Filled.Wysiwyg,
    "360" to Icons.AutoMirrored.Filled._360,
)
